### ISSUE TITLE
Not able to connect to table

### ISSUE THREAD

**Issue by vc13819** [GoogleCloudPlatform/cloud-bigtable-client#1063]
Something has changed recently.
This is our current setup.
An appengine project which houses the bigtable. We have created 1 cluster.

There we have 2 bigtables, one for prod and one for dev. (Clusters cost money..lots of it...tables are free)

Then we have 2 appengine projects, one for dev and one for prod which access the bigtable created previously (in the previous line:))

This was working fine for a while. Today when I tried to push a new binary, I started getting error that the project does not have bigtable admin API enabled (that is the project which is running dev). Fine, I enabled the api..did not help at all....

Question for you is that is it now not ok to access bigtable of one appengine project from another? (If so please please pretty please)

This is the error message verbatim:
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: PERMISSION_DENIED: Cloud Bigtable Admin API has not been used in project bigtable-dev before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/bigtableadmin.googleapis.com/overview?project=bigtable-dev then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.
	at com.google.bigtable.repackaged.io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230)
	at com.google.bigtable.repackaged.io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211)
	at com.google.bigtable.repackaged.io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
	at com.google.bigtable.admin.v2.BigtableInstanceAdminGrpc$BigtableInstanceAdminBlockingStub.listClusters(BigtableInstanceAdminGrpc.java:567)
	at com.google.cloud.bigtable.grpc.BigtableInstanceGrpcClient.listCluster(BigtableInstanceGrpcClient.java:95)
	at com.google.cloud.bigtable.grpc.BigtableClusterUtilities.getClusters(BigtableClusterUtilities.java:112)
	at com.google.cloud.bigtable.grpc.BigtableClusterUtilities.getCluster(BigtableClusterUtilities.java:222)
	at com.google.cloud.bigtable.grpc.BigtableClusterUtilities.lookupInstanceId(BigtableClusterUtilities.java:259)
	at com.google.cloud.bigtable.grpc.BigtableSession.resolveLegacyOptions(BigtableSession.java:305)
	at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:239)
	at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:137)
	at com.google.cloud.bigtable.hbase1_1.BigtableConnection.<init>(BigtableConnection.java:53)
	... 54 more

**Comment by vc13819** [comment]
Started working after a whle
