### ISSUE TITLE
Unable to use with emulator and no/fake default credentials

### ISSUE THREAD

**Issue by sdotz** [GoogleCloudPlatform/cloud-bigtable-client#1070]
I'm trying to use this with the emulator and without providing valid (or any) gcloud default application credentials but having issues.

I am passing BIGTABLE_EMULATOR_HOST

First the lib complains of not having a project ID. 
`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project seeder: An exception occured while executing the Java class. null: InvocationTargetException: Could not find an appropriate constructor for com.google.cloud.bigtable.hbase1_2.BigtableConnection: Project ID must be supplied via google.bigtable.project.id -> [Help 1]`

Is this relevant for the emulator? Let's plow forwards and give it that info.

Now I can see it outputs a line confirming it understood the BIGTABLE_EMULATOR_HOST.
`BigtableOptions:75 - Connecting to the Bigtable emulator at bigtable:8820`

but then...

`[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project seeder: An exception occured while executing the Java class. null: InvocationTargetException: Could not find an appropriate constructor for com.google.cloud.bigtable.hbase1_2.BigtableConnection: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information. -> [Help 1]`

We need application_default_credentials. Why?

If I provide real credentials things work, but if I fake them, it fails to auth. Is there some way to configure things so we deal with the emulator only and are not depending on this file and not phoning home to google cloud? It seems like once it sees BIGTABLE_EMULATOR_HOST it should understand not to do any auth stuff with gcloud. 

Thanks

**Comment by mbrukman** [comment]
If you are using the Bigtable emulator, you need to specify `BIGTABLE_EMULATOR_HOST` — your post talks about `PUBSUB_EMULATOR_HOST` instead, which is for another product: Google Cloud PubSub. Could that be the source of the issue?

See the [docs](https://cloud.google.com/bigtable/docs/emulator) for the details.

**Comment by sdotz** [comment]
Sorry, I pasted the wrong one. I am indeed using BIGTABLE_EMULATOR_HOST

**Comment by garye** [comment]
Are you using the hbase layer?

**Comment by sdotz** [comment]
Yes `com.google.cloud.bigtable.hbase1_2.BigtableConnection`

**Comment by garye** [comment]
Oh I see from the error message that you are. Perhaps there is a code path there that does something with credentials before it looks for the emulator env variable.

As for the project id, the emulator needs one but it could be any arbitrary string.

**Comment by sdotz** [comment]
I can't think of any path that does anything with the creds. It seems to happen when creating the bigtable session. Do you know if the emulator flag is supposed to route around this somehow?

```
Caused by: java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLust be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
 	at com.google.bigtable.repackaged.com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:74)
 	at com.google.bigtable.repackaged.com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:54)
 	at com.google.cloud.bigtable.config.CredentialFactory.getApplicationDefaultCredential(CredentialFactory.java:207)
 	at com.google.cloud.bigtable.config.CredentialFactory.getCredentials(CredentialFactory.java:112)
 	at com.google.cloud.bigtable.grpc.io.CredentialInterceptorCache.getCredentialsInterceptor(CredentialInterceptorCache.java:94)
 	at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:272)
 	at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:135)
 	at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:104)
 	at com.google.cloud.bigtable.hbase1_2.BigtableConnection.<init>(BigtableConnection.java:50)
 	... 14 more
```

**Comment by sdotz** [comment]
Ah this was fixed in 0.9.3. I was on 0.9.2. 

Fix was 99ab4a6ee5687cb60ecf3eaedb2552128d49c901 by Robert

The problem was in com.google.cloud.bigtable.config.BigtableOptions.Builder#applyEmulatorEnvironment
It was not setting null credentials and then later would default to default creds

**Comment by sdotz** [comment]
Thanks for the help!

**Comment by sduskis** [comment]
Glad you sorted it out :)
