### ISSUE TITLE
IncompatibleClassChangeError on moving to 0.9.4

### ISSUE THREAD

**Issue by vc13819** [GoogleCloudPlatform/cloud-bigtable-client#1110]
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238)
Caused by: java.lang.IncompatibleClassChangeError
at com.google.bigtable.repackaged.io.grpc.protobuf.lite.ProtoLiteUtils.marshaller(ProtoLiteUtils.java:80)
at com.google.bigtable.repackaged.io.grpc.protobuf.ProtoUtils.marshaller(ProtoUtils.java:71)

**Comment by vc13819** [comment]
Some more color...
I am moving from java7 to java8 as well with this move. (Now using jetty9-compat).
Using 0.9.3 gives the same error as well, so it is not related to 0.9.4.
The error persists though:(

**Comment by sduskis** [comment]
This seems like a classpath problem.  What bigtable related jars do you have on your classpath?

**Comment by sduskis** [comment]
I haven't heard back about this.  Please reopen the issue if this still a problem.
