### ISSUE TITLE
Unauthenticated exception in 0.9.4

### ISSUE THREAD

**Issue by vc13819** [GoogleCloudPlatform/cloud-bigtable-client#1141]
We are still facing the unauthenticated exception problem in 0.9.4. (The server was fine for more than a week, but in the last hour is acting up:( )

com.yawasa.server.ReadHandler doPost: READ Failed: com.yawasa.server.exception.StorageException$FailedRead
	at com.yawasa.server.storage.RawTopicTable.getWithoutHop(RawTopicTable.java:293)
	at com.yawasa.server.storage.RawTopicTable.get(RawTopicTable.java:220)
	at com.yawasa.server.storage.RawTopicTable.get(RawTopicTable.java:131)
	at com.yawasa.server.acl.AclTopicTable.get(AclTopicTable.java:90)
	at com.yawasa.server.ReadHandler.doPost(ReadHandler.java:47)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:51)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.doScope(VmRuntimeWebAppContext.java:308)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)

08:39:11.878
com.yawasa.server.ReadHandler doPost: CONTEXT: 
08:39:11.879
com.yawasa.server.ReadHandler doPost: java.util.concurrent.ExecutionException: java.lang.RuntimeException: com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.yawasa.server.storage.RawTopicTable.getWithoutHop(RawTopicTable.java:285)
	at com.yawasa.server.storage.RawTopicTable.get(RawTopicTable.java:220)
	at com.yawasa.server.storage.RawTopicTable.get(RawTopicTable.java:131)
	at com.yawasa.server.acl.AclTopicTable.get(AclTopicTable.java:90)
	at com.yawasa.server.ReadHandler.doPost(ReadHandler.java:47)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:51)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.doScope(VmRuntimeWebAppContext.java:308)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
	at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:97)
	at com.yawasa.server.storage.TopicReader.get(TopicReader.java:50)
	at com.yawasa.server.storage.RawTopicTable$3.call(RawTopicTable.java:267)
	at com.yawasa.server.storage.RawTopicTable$3.call(RawTopicTable.java:263)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 more
Caused by: com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
	at com.google.cloud.bigtable.grpc.scanner.ResultQueueEntry$ExceptionResultQueueEntry.getResponseOrThrow(ResultQueueEntry.java:88)
	at com.google.cloud.bigtable.grpc.scanner.ResponseQueueReader.getNextMergedRow(ResponseQueueReader.java:95)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:59)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:33)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:88)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:34)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient$8.next(BigtableDataGrpcClient.java:440)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient$8.next(BigtableDataGrpcClient.java:421)
	at com.google.cloud.bigtable.hbase.adapters.read.BigtableResultScannerAdapter$1.next(BigtableResultScannerAdapter.java:58)
	at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:94)
	... 9 more
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: UNAUTHENTICATED
	at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:503)
	at com.google.cloud.bigtable.grpc.scanner.StreamObserverAdapter.onClose(StreamObserverAdapter.java:61)
	at com.google.bigtable.repackaged.io.grpc.ClientInterceptors$CheckedForwardingClientCall.start(ClientInterceptors.java:203)
	at com.google.cloud.bigtable.grpc.async.BigtableAsyncUtilities$Default$1.start(BigtableAsyncUtilities.java:88)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.streamRows(BigtableDataGrpcClient.java:474)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.access$200(BigtableDataGrpcClient.java:87)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient$7.createScanner(BigtableDataGrpcClient.java:171)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient$7.createScanner(BigtableDataGrpcClient.java:168)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.<init>(ResumingStreamingResultScanner.java:79)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.<init>(ResumingStreamingResultScanner.java:62)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.readFlatRows(BigtableDataGrpcClient.java:457)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.readRows(BigtableDataGrpcClient.java:420)
	at com.google.cloud.bigtable.hbase.BigtableTable.getScanner(BigtableTable.java:240)
	... 9 more
Caused by: java.io.IOException: Could not read headers
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.refreshCredentialsWithRetry(RefreshingOAuth2CredentialsInterceptor.java:374)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.doRefresh(RefreshingOAuth2CredentialsInterceptor.java:304)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.syncRefresh(RefreshingOAuth2CredentialsInterceptor.java:227)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.getHeader(RefreshingOAuth2CredentialsInterceptor.java:256)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.updateHeaders(RefreshingOAuth2CredentialsInterceptor.java:197)
	at com.google.cloud.bigtable.grpc.io.ChannelPool$InstrumentedChannel$1.checkedStart(ChannelPool.java:157)
	at com.google.bigtable.repackaged.io.grpc.ClientInterceptors$CheckedForwardingClientCall.start(ClientInterceptors.java:195)
	... 19 more
<continued in next message>
08:39:11.879
<continued from previous message>
Caused by: com.google.apphosting.api.ApiProxy$ArgumentException: An error occurred parsing (locally or remotely) the arguments to APP_IDENTITY_SERVICE.GetAccessToken().
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.convertApiResponseRpcErrorToException(VmApiProxyDelegate.java:397)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.convertRemoteError(VmApiProxyDelegate.java:341)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.runSyncCall(VmApiProxyDelegate.java:187)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.makeApiCall(VmApiProxyDelegate.java:155)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.makeSyncCallWithTimeout(VmApiProxyDelegate.java:143)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.makeSyncCall(VmApiProxyDelegate.java:132)
	at com.google.apphosting.vmruntime.VmApiProxyDelegate.makeSyncCall(VmApiProxyDelegate.java:75)
	at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:114)
	at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:66)
	at com.google.appengine.api.appidentity.AppIdentityServiceImpl.getAccessTokenUncached(AppIdentityServiceImpl.java:232)
	at com.google.appengine.api.appidentity.AppIdentityServiceImpl.getAccessToken(AppIdentityServiceImpl.java:291)
	at com.google.bigtable.repackaged.com.google.auth.appengine.AppEngineCredentials.refreshAccessToken(AppEngineCredentials.java:77)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.refreshCredentialsWithRetry(RefreshingOAuth2CredentialsInterceptor.java:340)
	... 25 more

**Comment by sduskis** [comment]
I see `com.google.auth.appengine.AppEngineCredentials`.  We don't currently support AppEngine standard, which I'm guessing is the problem here.

If you need this feature, please talk to me off line (sduskis@google.com)

**Comment by sduskis** [comment]
Oh... is this AppEngine flex as per https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/1055?

**Comment by vc13819** [comment]
Yes.

**Comment by sduskis** [comment]
There isn't much I can do on this bug in the cloud bigtable client library.  Closing.
