### ISSUE TITLE
Exceptions thrown from HBaseMutationCoder and HBaseResultCoder

### ISSUE THREAD

**Issue by hadenlee** [GoogleCloudPlatform/cloud-bigtable-client#1145]
Hi,

I have fairly simple code that (1) scans a bigtable (successfully) to obtain PCollection<Result> (org.apache.hadoop.hbase.client.Result), (2) transforms it to PCollection<Mutation> (org.apache.hadoop.hbase.client.Mutation) by creating a put object out of each result object, (3) writes this PCollection to GCS using HBaseMutationCoder (com.google.cloud.bigtable.dataflow.coders.HBaseMutationCoder), (4) reads this PCollection<Mutation> from GCS using the same coder, and (5) writes it to a different bigtable. 

One pipeline performs (1), (2), and (3) (think of it as a dataflow job for backing up data) and another pipeline performs (4) and (5) (think of it as a dataflow job for recovering data).

The issue I am having is when the second pipeline performs step (4), it throws an exception [1] because it (for some reason) thinks that the mutation is not a 'put' but a 'delete' instead (although the first pipeline only created Put objects).  The code I used is attached at the end [2] (I am only showing the main parts to highlight what is being done, but the missing details should be obvious).

Another approach I used was to write PCollection<Result> after step (2) instead (using HBaseResultCoder), and the second pipeline would read this and create mutations out of Result objects. This approach also ended up with a bunch of exceptions [3].

On Stackoverflow, I asked about this (http://stackoverflow.com/questions/41052751/from-bigtable-to-gcs-and-vice-versa-via-dataflow), and was told to report an issue here.

If you wish to take a look at the jobs I ran on GCP, the first pipeline (steps 1-3) has job Id 2016-12-15_21_57_14-1967734925774841136 and the second pipeline (steps 4-5) has job id 2016-12-15_22_00_43-4149171962026702158 (which failed due to exceptions). 

Any help and suggestions will be greatly appreciated.
(I tested with 'com.google.cloud.bigtable:bigtable-hbase-dataflow:0.9.4' as well as 'com.google.cloud.bigtable:bigtable-hbase-dataflow:0.9.2' and had the same issues.)

[1] The exception thrown:
`Caused by: java.lang.IllegalArgumentException: DeleteAdapter does not support MUTATION_NOT_SET.
	at com.google.bigtable.repackaged.com.google.cloud.hbase.adapters.DeleteAdapter.adapt(DeleteAdapter.java:202)
	at com.google.cloud.bigtable.dataflow.coders.HBaseMutationCoder.decode(HBaseMutationCoder.java:72)
	at com.google.cloud.bigtable.dataflow.coders.HBaseMutationCoder.decode(HBaseMutationCoder.java:41)
	at com.google.cloud.dataflow.sdk.io.TextIO$TextSource$TextBasedReader.decodeCurrentElement(TextIO.java:1021)
	at com.google.cloud.dataflow.sdk.io.TextIO$TextSource$TextBasedReader.readNextRecord(TextIO.java:1008)
	at com.google.cloud.dataflow.sdk.io.FileBasedSource$FileBasedReader.advanceImpl(FileBasedSource.java:507)
	at com.google.cloud.dataflow.sdk.io.FileBasedSource$FileBasedReader.startImpl(FileBasedSource.java:502)
	at com.google.cloud.dataflow.sdk.io.OffsetBasedSource$OffsetBasedReader.start(OffsetBasedSource.java:279)
	at com.google.cloud.dataflow.sdk.runners.worker.WorkerCustomSources$BoundedReaderIterator.start(WorkerCustomSources.java:534)
	... 14 more`

[2] The code I used which threw exceptions like the one above.

`

    // To scan bigtable and dump to GCS.
    {
      Pipeline pipeline = Pipeline.create(options);
      Scan scan = new Scan();
      scan.setCacheBlocks(false).setMaxVersions(1);
      scan.addFamily(Bytes.toBytes(cf));
      CloudBigtableScanConfiguration btConfig = new CloudBigtableScanConfiguration.Builder().withProjectId(project)
          .withInstanceId(clusterId).withTableId(tableId).withScan(scan).build();
      PCollection<Result> result = pipeline.apply(Read.from(CloudBigtableIO.read(btConfig)));
      PCollection<Mutation> mutation =
          result.apply(ParDo.of(new CreateMutationFromResult())).setCoder(new HBaseMutationCoder());
      mutation.apply(TextIO.Write.to("gs://dataflow-experimental/bigtable-dump/test/scan-result")
          .withCoder(new HBaseMutationCoder()));
      pipeline.run();
    }

    // To read dumped data and write to bigtable.
    {
      Pipeline pipeline = Pipeline.create(options);
      PCollection<Mutation> mutations =
          pipeline.apply(TextIO.Read.from("gs://dataflow-experimental/bigtable-dump/test/scan-result*")
              .withCoder(new HBaseMutationCoder())).setCoder(new HBaseMutationCoder());
      CloudBigtableScanConfiguration btConfig = new CloudBigtableScanConfiguration.Builder().withProjectId(project)
          .withInstanceId(clusterId).withTableId(tableId).build();
      if (btConfig != null) {
        CloudBigtableIO.initializeForWrite(pipeline);
        mutations.apply(CloudBigtableIO.writeToTable(btConfig));
      }
      pipeline.run();
    }
    // ..... processElement of CreateMutationFromResult class above:
    public void processElement(ProcessContext c) {
      Result result = c.element();
      byte[] row = result.getRow();
      if (row != null && row.length > 0) {
        Put put = new Put(row);
        for (Cell cell : result.rawCells()) {
          try {
            put.add(cell);
          } catch (IOException e) {
          }
          // put.addImmutable(cell.getFamily(), cell.getQualifier(), cell.getValue());
        }
        c.output(put);
      }
    }
`

[3] If I were to write PCollection<Result> to GCS and read it using HBaseResultCoder, I would get the following exception:

`
(fdb6f7b30585573e): java.io.IOException: Failed to start reading from source: gs://dataflow-experimental/bigtable-dump/test/result/scan-result-00000-of-00001 range [574070, 1148140)
	at com.google.cloud.dataflow.sdk.runners.worker.WorkerCustomSources$BoundedReaderIterator.start(WorkerCustomSources.java:537)
	at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation$SynchronizedReaderIterator.start(ReadOperation.java:390)
	at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:220)
	at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.start(ReadOperation.java:185)
	at com.google.cloud.dataflow.sdk.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:72)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.executeWork(DataflowWorker.java:287)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.doWork(DataflowWorker.java:223)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.getAndPerformWork(DataflowWorker.java:173)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.doWork(DataflowWorkerHarness.java:193)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:173)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:160)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.bigtable.repackaged.com.google.protobuf.InvalidProtocolBufferException: Protocol message tag had invalid wire type.
	at com.google.bigtable.repackaged.com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:111)
	at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.skipField(CodedInputStream.java:201)
	at com.google.bigtable.repackaged.com.google.com.google.bigtable.v2.Row.<init>(Row.java:47)
	at com.google.bigtable.repackaged.com.google.com.google.bigtable.v2.Row.<init>(Row.java:14)
	at com.google.bigtable.repackaged.com.google.com.google.bigtable.v2.Row$1.parsePartialFrom(Row.java:907)
	at com.google.bigtable.repackaged.com.google.com.google.bigtable.v2.Row$1.parsePartialFrom(Row.java:902)
	at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:197)
	at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parsePartialDelimitedFrom(AbstractParser.java:238)
	at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:251)
	at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:256)
	at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseDelimitedFrom(AbstractParser.java:49)
	at com.google.bigtable.repackaged.com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(GeneratedMessageV3.java:318)
	at com.google.bigtable.repackaged.com.google.com.google.bigtable.v2.Row.parseDelimitedFrom(Row.java:278)
	at com.google.cloud.bigtable.dataflow.coders.HBaseResultCoder.decode(HBaseResultCoder.java:45)
	at com.google.cloud.bigtable.dataflow.coders.HBaseResultCoder.decode(HBaseResultCoder.java:32)
	at com.google.cloud.dataflow.sdk.io.TextIO$TextSource$TextBasedReader.decodeCurrentElement(TextIO.java:1021)
	at com.google.cloud.dataflow.sdk.io.TextIO$TextSource$TextBasedReader.readNextRecord(TextIO.java:1008)
	at com.google.cloud.dataflow.sdk.io.FileBasedSource$FileBasedReader.advanceImpl(FileBasedSource.java:507)
	at com.google.cloud.dataflow.sdk.io.FileBasedSource$FileBasedReader.startImpl(FileBasedSource.java:502)
	at com.google.cloud.dataflow.sdk.io.OffsetBasedSource$OffsetBasedReader.start(OffsetBasedSource.java:279)
	at com.google.cloud.dataflow.sdk.runners.worker.WorkerCustomSources$BoundedReaderIterator.start(WorkerCustomSources.java:534)
	... 14 more
`

**Comment by sduskis** [comment]
HBaseMutationCoder doesn't think this is a Delete, it just thinks its not a Put.  [Here](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-dataflow-parent/bigtable-hbase-dataflow/src/main/java/com/google/cloud/bigtable/dataflow/coders/HBaseMutationCoder.java#L73)'s the specific line in question.

I think that the Delete vs. Put issue is not the main issue here.  I've had various issues getting TextIO.Write / TextIO.Read to work properly.  I'm going to reach out to the Dataflow developers to figure out how to best implement this kind of feature.  I think that the likely answer will be to use AvroIO rather than TextIO, but I'm not completely sure.

**Comment by hadenlee** [comment]
Thanks for the clarification!
Sorry I was not clear -- that was what I meant by "the mutation is not a 'put' but a 'delete' instead" (as it skips the if-statement and moves on to the else-statement).

Given that HBase[Mutation|Result]Coder aren't working as expected for the time being, do you have any other suggestions for doing this? The only idea I have is to create a new class (whose instance would contain row key, qualifier, and value) and write a new coder myself, but other suggestions will be very helpful.

Thanks for getting back to me quickly, as I was not sure if I was completely missing something.

**Comment by sduskis** [comment]
HBase[Mutation|Result]Coder work as they were intended.  I think the problem is that TextIO is the wrong solution to store the data.  I'm going to explore AvroIO as an alternative, and if you're up for looking at it as well, all the better.

**Comment by hadenlee** [comment]
I'm not very familiar with how Coders interact with TextIO, but are you suggesting that even if Coders work correctly, they may not be compatible with Dataflow SDK's TextIO? 
My team considered using AvroIO, but having to specify schema seems to introduce an overhead which we really want to avoid (and I thought that was the benefit of having cloud bigtable client's connector package). I look forward to any leads you may have on this issue. Thanks!

**Comment by sduskis** [comment]
[TextIO](https://cloud.google.com/dataflow/model/text-io) is new line delimited.  The Coders we wrote are meant to transfer individual Mutations / Results across machines so that Dataflow can shuffle objects between workers for better balancing of work.  The Coders produce a set of bytes, which may contain new lines; that's a fine thing for a Coder to do, but will mess with TextIO's ability to restore objects intact.  My understanding from the Dataflow team that AvroIO's schema's work better for this scenario.

**Comment by sduskis** [comment]
This isn't something that we'll be fixing.  We can consider creating an Avro exporter, but that's not in scope for now.  Cloud Bigtable provides a method of [importing](https://cloud.google.com/bigtable/docs/importing-sequence-files) and [exporting](https://cloud.google.com/bigtable/docs/exporting-sequence-files) sequence files.
