### ISSUE TITLE
Problem doing a read with 0.9.5.1 version on App Engine.

### ISSUE THREAD

**Issue by vc13819** [GoogleCloudPlatform/cloud-bigtable-client#1223]
I am unable to do reads when using 0.9.5.1 version. The code works fine with 0.9.4 though.

Attached is the [code](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/files/783879/backend.zip) which reproduces the problem. For most part, this is adapted from the gae-flex example. A connection to the bigtable is created using a servletcontext weblistener. The connection is then used in a servlet to do a scan.
The error I get is that is
The root cause appears to be
"Caused by: java.lang.IllegalStateException: Request threads can only be created within the context of a running request".

The entire stacktrace.

22:39:07.288
com.yawasa.server.ReadHandler doPost: java.lang.RuntimeException: com.google.cloud.bigtable.grpc.scanner.BigtableRetriesExhaustedException: Exhausted streaming retries.
	at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:97)
	at com.yawasa.server.ReadHandler.doPost(ReadHandler.java:31)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:51)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.doScope(VmRuntimeWebAppContext.java:312)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:306)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.cloud.bigtable.grpc.scanner.BigtableRetriesExhaustedException: Exhausted streaming retries.
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:88)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:34)
	at com.google.cloud.bigtable.hbase.adapters.read.BigtableResultScannerAdapter$1.next(BigtableResultScannerAdapter.java:57)
	at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:94)
	... 35 more
Caused by: com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
	at com.google.cloud.bigtable.grpc.scanner.ResultQueueEntry$ExceptionResultQueueEntry.getResponseOrThrow(ResultQueueEntry.java:88)
	at com.google.cloud.bigtable.grpc.scanner.ResponseQueueReader.getNextMergedRow(ResponseQueueReader.java:91)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:79)
	... 38 more
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: UNKNOWN
	at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:530)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingRpcListener.onClose(AbstractRetryingRpcListener.java:149)
	at com.google.cloud.bigtable.grpc.scanner.ReadRowsRetryListener.onClose(ReadRowsRetryListener.java:141)
	at com.google.bigtable.repackaged.io.grpc.ClientInterceptors$CheckedForwardingClientCall.start(ClientInterceptors.java:202)
	at com.google.cloud.bigtable.grpc.async.BigtableAsyncUtilities$Default$1.start(BigtableAsyncUtilities.java:88)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingRpcListener.run(AbstractRetryingRpcListener.java:224)
	at com.google.cloud.bigtable.grpc.scanner.ReadRowsRetryListener.run(ReadRowsRetryListener.java:99)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingRpcListener.start(AbstractRetryingRpcListener.java:236)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.createReadRowsRetryListener(BigtableDataGrpcClient.java:464)
	at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.readFlatRows(BigtableDataGrpcClient.java:443)
	at com.google.cloud.bigtable.hbase.BigtableTable.getScanner(BigtableTable.java:273)
	at com.yawasa.server.ReadHandler.doPost(ReadHandler.java:32)
	... 34 more
Caused by: java.lang.IllegalStateException: Request threads can only be created within the context of a running request.
	at com.google.appengine.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:449)
	at com.google.apphosting.vmruntime.VmRequestThreadFactory.newThread(VmRequestThreadFactory.java:73)
	at com.google.bigtable.repackaged.com.google.common.util.concurrent.ThreadFactoryBuilder$1.newThread(ThreadFactoryBuilder.java:162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1587)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl.rescheduleIdleTimer(ManagedChannelImpl.java:358)
	at com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl.exitIdleMode(ManagedChannelImpl.java:294)
	at com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl.exitIdleModeAndGetLb(ManagedChannelImpl.java:268)
	at com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl$2.get(ManagedChannelImpl.java:379)
	at com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl.start(ClientCallImpl.java:216)
	at com.google.cloud.bigtable.grpc.io.ChannelPool$InstrumentedChannel$1.checkedStart(ChannelPool.java:168)
	at com.google.bigtable.repackaged.io.grpc.ClientInterceptors$CheckedForwardingClientCall.start(ClientInterceptors.java:194)
	... 42 more

**Comment by sduskis** [comment]
I'm going to need some help from the grpc and appengine teams on this one.  I'll see if I can get some traction with those teams.

Cloud Bigtable 0.9.4 uses grpc 0.14.1, while 0.9.5.1 use grpc 1.0.3.  This seems to be a grpc behavior change that happened with the upgrade:

> com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl.rescheduleIdleTimer(ManagedChannelImpl.java:358)

**Comment by vc13819** [comment]
ping

**Comment by sduskis** [comment]
I pinged the grpc team.  They suggested a change to disable the idle timer.  I'll get to that today.

**Comment by vc13819** [comment]
Nice!!
Do let me know once we have a snapshot we can test.
Thanks

**Comment by sduskis** [comment]
I deployed 0.9.6-SNAPSHOT.  Please feel free to try it out.

**Comment by vc13819** [comment]
Hmm...did not quite work.
I ran a loadtest and this was a consistent observation across multiple
runs. Screenshot attached.

The first request to the server always ends with this curious message.
(Though subsequent runs succeed).
com.google.apphosting.vmruntime.VmRequestThreadFactory
interruptRequestThreads: Request thread grpc-default-executor-0 is still
alive, forcing interrupt.
Seems like a curious message, did we just lose a thread from the pool?

The performance deteriorates for some set of requests. For a single server
I notice that there is a periodic cadence of slow requests (every 3rd
starts taking seconds while the other 2 finish in 40'ish ms. The requests
are randomly made in the loadtest).

In a few runs I even got this error: (Seems like the same error as before).
Though previously this error would come in the first request if the
connection was initialized in a weblistener and used in a servlet (similar
to the flex example). Now it takes time.

Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException:
UNKNOWN: Name resolution failed at
com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(
Status.java:530
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2FStatus.java&line=530&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at com.google.cloud.bigtable.grpc.async.AbstractRetryingRpcListener.onClose(
AbstractRetryingRpcListener.java:149
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fcloud%2Fbigtable%2Fgrpc%2Fasync%2FAbstractRetryingRpcListener.java&line=149&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at com.google.cloud.bigtable.grpc.scanner.ReadRowsRetryListener.onClose(
ReadRowsRetryListener.java:141
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fcloud%2Fbigtable%2Fgrpc%2Fscanner%2FReadRowsRetryListener.java&line=141&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.cloud.bigtable.grpc.io.ChannelPool$InstrumentedChannel$2.onClose(
ChannelPool.java:209
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fcloud%2Fbigtable%2Fgrpc%2Fio%2FChannelPool.java&line=209&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl.closeObserver(
ClientCallImpl.java:422
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FClientCallImpl.java&line=422&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl.access$100(
ClientCallImpl.java:74
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FClientCallImpl.java&line=74&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(
ClientCallImpl.java:508
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FClientCallImpl.java&line=508&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(
ClientCallImpl.java:425
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FClientCallImpl.java&line=425&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(
ClientCallImpl.java:540
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FClientCallImpl.java&line=540&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at com.google.bigtable.repackaged.io.grpc.internal.ContextRunnable.run(
ContextRunnable.java:52
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FContextRunnable.java&line=52&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.SerializingExecutor$TaskRunner.run(
SerializingExecutor.java:152
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FSerializingExecutor.java&line=152&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
... 1 more Caused by: java.lang.IllegalStateException: Cannot create new
threads after the request thread stops. at
com.google.appengine.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:449)
at
com.google.apphosting.vmruntime.VmRequestThreadFactory.newThread(VmRequestThreadFactory.java:87)
at
com.google.bigtable.repackaged.com.google.common.util.concurrent.ThreadFactoryBuilder$1.newThread(
ThreadFactoryBuilder.java:162
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fcom%2Fgoogle%2Fcommon%2Futil%2Fconcurrent%2FThreadFactoryBuilder.java&line=162&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.java:612)
at
java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:925)
at
java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1368)
at com.google.bigtable.repackaged.io.grpc.internal.DnsNameResolver.resolve(
DnsNameResolver.java:205
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FDnsNameResolver.java&line=205&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at com.google.bigtable.repackaged.io.grpc.internal.DnsNameResolver.start(
DnsNameResolver.java:116
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FDnsNameResolver.java&line=116&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl$1NameResolverStartTask.run(
ManagedChannelImpl.java:315
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FManagedChannelImpl.java&line=315&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl.exitIdleModeAndGetLb(
ManagedChannelImpl.java:272
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FManagedChannelImpl.java&line=272&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl$2.get(
ManagedChannelImpl.java:379
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FManagedChannelImpl.java&line=379&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at com.google.bigtable.repackaged.io.grpc.internal.ClientCallImpl.start(
ClientCallImpl.java:216
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2Finternal%2FClientCallImpl.java&line=216&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.cloud.bigtable.grpc.io.ChannelPool$InstrumentedChannel$1.checkedStart(
ChannelPool.java:168
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fcloud%2Fbigtable%2Fgrpc%2Fio%2FChannelPool.java&line=168&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.bigtable.repackaged.io.grpc.ClientInterceptors$CheckedForwardingClientCall.start(
ClientInterceptors.java:194
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fbigtable%2Frepackaged%2Fio%2Fgrpc%2FClientInterceptors.java&line=194&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at
com.google.cloud.bigtable.grpc.async.BigtableAsyncUtilities$Default$1.start(
BigtableAsyncUtilities.java:88
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fcloud%2Fbigtable%2Fgrpc%2Fasync%2FBigtableAsyncUtilities.java&line=88&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at com.google.cloud.bigtable.grpc.async.AbstractRetryingRpcListener.run(
AbstractRetryingRpcListener.java:224
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fcloud%2Fbigtable%2Fgrpc%2Fasync%2FAbstractRetryingRpcListener.java&line=224&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
at com.google.cloud.bigtable.grpc.scanner.ReadRowsRetryListener.run(
ReadRowsRetryListener.java:99
<https://console.cloud.google.com/debug/fromlog?appModule=vinay&appVersion=20170301t073607&file=com%2Fgoogle%2Fcloud%2Fbigtable%2Fgrpc%2Fscanner%2FReadRowsRetryListener.java&line=99&logInsertId=58b632d30007bab4f6f2ef13&logNanos=1488335570938113000&nestedLogIndex=0&project=bigtable-dev>)
<continued in next message>

All the runs were done with exactly one server. (If the servers are
elastic, this error is harder to reproduce)

What is the recommended setup to use cloud bigtable. Is there a non-flex
setup that you recommend (GCE perhaps?, or a non-compat jar?)

**Comment by vc13819** [comment]
Wondering if this is somehow relevant:
https://github.com/grpc/grpc-java/issues/80

**Comment by vc13819** [comment]
One more potential lead
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/pull/1125/files
As mentioned before, the first request finishes with this error message:
com.google.apphosting.vmruntime.VmRequestThreadFactory
interruptRequestThreads: Request thread grpc-default-executor-0 is still
alive, forcing interrupt.

This PR propagates the interrupts to the thread. The timing of this PR is also in the range of interest, it is after 0.9.4 (which was the last version I could get to work on flex)

**Comment by sduskis** [comment]
The problem is still related to the idle scheduler:

> com.google.bigtable.repackaged.io.grpc.internal.ManagedChannelImpl.exitIdleModeAndGetLb(
> ManagedChannelImpl.java:272

I'll pass this back to the gRPC team, since this isn't a Bigtable specific problem.  For the record, 0.9.4 used a much older version of gRPC (0.14.1).  0.9.5.1 upgraded to 1.03, and 0.9.6-SNAPSHOT is at 1.1.1 and will be 1.1.2.  We'll need to do more gRPC testing on App Engine.

**Comment by vc13819** [comment]
FYI So I moved to the non-compat version of flex. Its been about a week, and things look stable.

**Comment by sduskis** [comment]
I'm glad you solved it.  Sorry we weren't more help.
