### ISSUE TITLE
Dependency conflicts after 0.9.5.1 upgrade

### ISSUE THREAD

**Issue by Naveg** [GoogleCloudPlatform/cloud-bigtable-client#1224]
We ran into some issues when trying to upgrade to 0.9.5.1. Seems like it might be a Jersey version conflict.

We are using `bigtable-hbase-shaded`, instead of `bigtable-hbase-1.2`, as we always had similar problems with the latter.

The bigtable client is integrated into a project that uses dropwizard.

This issue seems similar: https://github.com/testcontainers/testcontainers-java/issues/68

Some sample exceptions we are seeing:

```
MultiException stack 1 of 2
java.lang.NullPointerException
        at com.sun.jersey.core.provider.jaxb.AbstractJAXBProvider.setConfiguration(AbstractJAXBProvider.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


MultiException stack 2 of 2
java.lang.IllegalStateException: Unable to perform operation: method inject on com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$App
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:392)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2020)


MultiException stack 2 of 3
java.lang.IllegalStateException: Unable to perform operation: method inject on com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$App
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:392)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:70)
        at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2020)


MultiException stack 3 of 3
java.lang.IllegalStateException: Unable to perform operation: create on org.glassfish.jersey.message.internal.MessageBodyFactory
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:386)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
        at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:83)
```

I'll keep working on this as time permits, but any insight would be appreciated. I never have much luck sorting out dependency problems.

**Comment by igorbernstein2** [comment]
Hi Naveg,

I haven't been able to reproduce this issue. I tried with dropwizard 0.9.2 and 1.0.6.
Would you mind posting some more information about your dependencies? If possible, posting the <dependencies> section of the effective pom (`mvn help:effective-pom`) would help me reproduce the error.

Thanks

**Comment by Naveg** [comment]
We use gradle, so I can't run `mvn help:effective-pom` (is there an equivalent that would be helpful?), but these are our top level dependencies:

```
assertJ: 'org.assertj:assertj-core:3.6.2',
bcrypt: 'de.svenkubiak:jBCrypt:0.4.1',
bigtable: 'com.google.cloud.bigtable:bigtable-hbase-shaded:0.9.4',
config: 'commons-configuration:commons-configuration:1.10',
dropwizard: 'io.dropwizard:dropwizard-core:1.0.5',
dropwizard_auth: 'io.dropwizard:dropwizard-auth:1.0.5',
dropwizard_test: 'io.dropwizard:dropwizard-testing:1.0.5',
dropwizard_graphite: 'io.dropwizard:dropwizard-metrics-graphite:1.0.5',
flyway: 'org.flywaydb:flyway-core:4.0.3',
flyway_gradle: 'org.flywaydb:flyway-gradle-plugin:4.0.3',
guava: 'com.google.guava:guava:19.0',
guice: 'com.google.inject:guice:4.1.0',
hbase: 'org.apache.hbase:hbase-shaded-client:1.2.4',
hikaricp: 'com.zaxxer:HikariCP:2.6.0',
jackson: 'io.dropwizard:dropwizard-jackson:1.0.5',
jedis: 'redis.clients:jedis:2.9.0',
jool: 'org.jooq:jool:0.9.12',
jooq: 'org.jooq:jooq:3.9.1',
jooq_codegen: 'org.jooq:jooq-codegen:3.9.1',
junit: 'junit:junit:4.12',
jwt: 'io.jsonwebtoken:jjwt:0.7.0',
metrics: 'io.dropwizard.metrics:metrics-core:3.1.2',
netty: 'io.netty:netty-tcnative-boringssl-static:1.1.33.Fork19',
mockito: 'org.mockito:mockito-core:2.6.8',
poi: 'org.apache.poi:poi:3.15',
poi_ooxml: 'org.apache.poi:poi-ooxml:3.15',
postgres: 'org.postgresql:postgresql:9.4.1212',
pubsub: 'com.google.apis:google-api-services-pubsub:v1-rev20-1.22.0',
sendgrid: 'com.sendgrid:sendgrid-java:2.2.2',
slf4j: 'org.slf4j:slf4j-api:1.7.22',
snappy: 'org.xerial.snappy:snappy-java:1.1.2.6',
spring_aop: 'org.springframework:spring-aop:4.3.6.RELEASE',
spring_jdbc: 'org.springframework:spring-jdbc:4.3.6.RELEASE',
spring_tx: 'org.springframework:spring-tx:4.3.6.RELEASE',
trimou: 'org.trimou:trimou-core:2.1.0.Final',
vault_java_driver: 'com.bettercloud:vault-java-driver:1.2.0'
```

**Comment by igorbernstein2** [comment]
I think the issue is caused by gradle not respecting maven's exclusions:
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-hbase-parent/bigtable-hbase/pom.xml#L76

I think you can workaround this issue by including the bigtable hbase client without transitive dependencies:

```gradle
    compile('com.google.cloud.bigtable:bigtable-hbase-1.2:0.9.5.1') {
        transitive = false
    }
```

**Comment by Naveg** [comment]
That works - thanks!
