### ISSUE TITLE
bigtable-protos:0.9.2 clash with grpc-google-common-protos:0.1.6

### ISSUE THREAD

**Issue by dysosmus** [GoogleCloudPlatform/cloud-bigtable-client#1225]
Both packages are using the namespace `com.google.rpc`  which make them unusable in the same project with errors like:

(when used with google-cloud-spanner:0.9.2-beta, that include grpc-google-common-protos:0.1.6 as dependency) 

edit: also tested with bigtable-protos:0.9.5 

```
Exception in thread "main" java.lang.NoSuchFieldError: internal_static_google_rpc_LocalizedMessage_fieldAccessorTable
        at com.google.rpc.LocalizedMessage.internalGetFieldAccessorTable(LocalizedMessage.java:82)
        at com.google.protobuf.GeneratedMessageV3.getDescriptorForType(GeneratedMessageV3.java:109)
        at io.grpc.protobuf.ProtoUtils.keyForProto(ProtoUtils.java:127)
        at com.google.cloud.spanner.spi.SpannerErrorInterceptor.<clinit>(SpannerErrorInterceptor.java:47)
        at com.google.cloud.spanner.spi.DefaultSpannerRpc.<init>(DefaultSpannerRpc.java:128)
        at com.google.cloud.spanner.SpannerOptions$DefaultSpannerRpcFactory.create(SpannerOptions.java:66)
        at com.google.cloud.spanner.SpannerOptions$DefaultSpannerRpcFactory.create(SpannerOptions.java:61)
        at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:484)
        at com.google.cloud.spanner.SpannerImpl.<init>(SpannerImpl.java:136)
        at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:56)
        at com.google.cloud.spanner.SpannerOptions$DefaultSpannerFactory.create(SpannerOptions.java:51)
        at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:471)
        at com.messagebird.spannertest.Foo.main(Foo.java:12)
```

**Comment by dysosmus** [comment]
fixed by #1230
