### ISSUE TITLE
Bigtable lib does not work (yet) with GAE Standard Java7

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/cloud-bigtable-client#1243]
Hi,
I modified a bit the sample we did back in November to target the Java8 GAE standard runtime, which is still working.
But when targetting the current Java7 runtime, I get this exception:
https://bigtablejava7-dot-pubrobots.appspot.com/
Uncaught exception from servlet
java.lang.ExceptionInInitializerError
	at com.google.appengine.runtime.Request.process-c13da91a8ab38418(Request.java)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:138)
	at com.google.cloud.bigtable.hbase.BigtableConfiguration.chooseConnectionClass(BigtableConfiguration.java:43)
	at com.google.cloud.bigtable.hbase.BigtableConfiguration.<clinit>(BigtableConfiguration.java:37)
	at com.example.cloud.bigtable.helloworld.BigtableHelper.connect(BigtableHelper.java:57)
	at com.example.cloud.bigtable.helloworld.BigtableHelper.contextInitialized(BigtableHelper.java:78)
	at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:548)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:136)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:454)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:461)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:276)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:320)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:312)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:458)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThreadGroup")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:484)
	at java.security.AccessController.checkPermission(AccessController.java:698)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
	at java.lang.Thread.init(Thread.java:391)
	at java.lang.Thread.init(Thread.java:349)
	at java.lang.Thread.<init>(Thread.java:461)
	at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<clinit>(AbstractBigtableConnection.java:75)
	... 19 more

So it seems the BT client library is not using the AppEngine Specific threadmanager necessary for GAE Java7 runtime.
It is fine with Java8 GAE which does not impose a security manager.

See https://cloud.google.com/appengine/docs/standard/java/javadoc/com/google/appengine/api/ThreadManager for the code to use only when Java7 and GAE (not Java8 and GAE)

**Comment by ludoch** [comment]
@sduskis FYI, now that Java7 GAE runtime can support GRPC client based library, we need to do this change.

**Comment by ludoch** [comment]
@lesv FYI

**Comment by aramparonikyan-scdm** [comment]
@ludoch Hi, could you please confirm that you have succeeded in opening a connection to Bigtable from Standard GAE w/java8? If there is a quick solution/link, I would be thankful for sharing!

**Comment by lesv** [comment]
@aramparonikyan-scdm I can confirm that we've done it.  I can't yet confirm that it works in the public client.  I had planned to look into this, again, early next month, @sduskis might be able to say if it works now, however.

**Comment by sduskis** [comment]
@aramparonikyan-scdm: There was a gRPC change that caused problems in our 0.9.5.1 release in AppEngine.  The 0.9.4 release should (hopefully) work on GAE Standard java8.

**Comment by sduskis** [comment]
@ludoch, I submitted a fix, but I'd need some help testing it.  I use GrpcUtil's implementation of threadpool managers, which uses the appengine ThreadManager for JDK 7 / AppEngine scenarios.

Also, please update your November sample to use the 0.9.5.1 Cloud Bigtable client version.

**Comment by sduskis** [comment]
The client works on App Engine.
