### ISSUE TITLE
BigtableConfiguration fails to find BigtableConnection class in using bigtable-hbase-1.3:0.9.6

### ISSUE THREAD

**Issue by ankurcha** [GoogleCloudPlatform/cloud-bigtable-client#1273]
When using the bigtable-hbase-1.2 package the creation of `BigtableConfiguration.configure(projectId, instanceId);` fails with the following error. 

Based on the code in [BigtableConfiguration](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-hbase-parent/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableConfiguration.java#L30) Line 30, the list of classes to check does not contain the `com.google.cloud.bigtable.hbase1_3.BigtableConnection` class. The fix would be pretty simple as the class actually does exist but does is not being checked for.

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.hadoop.hbase.client.Connection]: Factory method 'connection' threw exception; nested exception is java.lang.IllegalStateException: Could not find an appropriate BigtableConnection class
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 48 common frames omitted
Caused by: java.lang.IllegalStateException: Could not find an appropriate BigtableConnection class
	at com.google.bigtable.repackaged.com.google.api.client.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:176)
	at com.google.cloud.bigtable.hbase.BigtableConfiguration.getConnectionClass(BigtableConfiguration.java:55)
	at com.google.cloud.bigtable.hbase.BigtableConfiguration.configure(BigtableConfiguration.java:83)
	at com.google.cloud.bigtable.hbase.BigtableConfiguration.configure(BigtableConfiguration.java:69)
	at com.brightcove.rna.config.BigtableConnectionAutoConfiguration.connection(BigtableConnectionAutoConfiguration.java:34)
	at com.brightcove.rna.config.BigtableConnectionAutoConfiguration$$EnhancerBySpringCGLIB$$f009ac7c.CGLIB$connection$3(<generated>)
	at com.brightcove.rna.config.BigtableConnectionAutoConfiguration$$EnhancerBySpringCGLIB$$f009ac7c$$FastClassBySpringCGLIB$$d36b7776.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:356)
	at com.brightcove.rna.config.BigtableConnectionAutoConfiguration$$EnhancerBySpringCGLIB$$f009ac7c.connection(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 49 common frames omitted
```

Current workaround is to create the class manually or use hbase-1.2 or hbase-1.1 versions of the package:

```java
Connection connection(String projectId, String instanceId) throws IOException {
        org.apache.hadoop.conf.Configuration conf = new org.apache.hadoop.conf.Configuration(false);
        conf.set(BigtableOptionsFactory.PROJECT_ID_KEY, projectId);
        conf.set(BigtableOptionsFactory.INSTANCE_ID_KEY, instanceId);
        conf.set(HConnection.HBASE_CLIENT_CONNECTION_IMPL, com.google.cloud.bigtable.hbase1_3.BigtableConnection.class.getCanonicalName());
        return new com.google.cloud.bigtable.hbase1_3.BigtableConnection(conf);
    }
```

**Comment by sduskis** [comment]
I'll fix this for 0.9.6.1 as well.

**Comment by sduskis** [comment]
I'm deploying an 0.9.7-SNAPSHOT with this feature.  See #1275 for details on how to use the SNAPSHOT and further release planning.

**Comment by ankurcha** [comment]
Thanks. I will use the snapshot for now.

**Comment by alikini** [comment]
Hello , we facing the same issue ! . 
Can't get it work with sbt:     "com.google.cloud.bigtable" % "bigtable-hbase" % "1.3.0"

Please help ASAP.

10x
