### ISSUE TITLE
Inclusion of google well known proto types makes it impossible to use other services

### ISSUE THREAD

**Issue by ankurcha** [GoogleCloudPlatform/cloud-bigtable-client#1274]
The version 0.9.6 bigtable-client package includes all the `com.google.type` classes but remaps the `com.google.protobuf.Descriptors.FileDescriptor` to `repackaged` package. This makes it impossible to use for example datastore in the same project as it may encounter the repackaged version of the class before the "real" version from `grpc-google-common`. 
Causing an error:

```
Caused by: java.lang.NoSuchMethodError: com.google.type.LatLngProto.getDescriptor()Lcom/google/protobuf/Descriptors$FileDescriptor;
	at com.google.datastore.v1.EntityProto.<clinit>(EntityProto.java:107)
	at com.google.datastore.v1.Entity$PropertiesDefaultEntryHolder.<clinit>(Entity.java:160)
	at com.google.datastore.v1.Entity.<init>(Entity.java:67)
	at com.google.datastore.v1.Entity.<init>(Entity.java:16)
	at com.google.datastore.v1.Entity$1.parsePartialFrom(Entity.java:1014)
	at com.google.datastore.v1.Entity$1.parsePartialFrom(Entity.java:1009)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
	at com.google.datastore.v1.EntityResult.<init>(EntityResult.java:56)
	at com.google.datastore.v1.EntityResult.<init>(EntityResult.java:13)
	at com.google.datastore.v1.EntityResult$1.parsePartialFrom(EntityResult.java:922)
	at com.google.datastore.v1.EntityResult$1.parsePartialFrom(EntityResult.java:917)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
	at com.google.datastore.v1.QueryResultBatch.<init>(QueryResultBatch.java:68)
	at com.google.datastore.v1.QueryResultBatch.<init>(QueryResultBatch.java:13)
	at com.google.datastore.v1.QueryResultBatch$1.parsePartialFrom(QueryResultBatch.java:1521)
	at com.google.datastore.v1.QueryResultBatch$1.parsePartialFrom(QueryResultBatch.java:1516)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readMessage(CodedInputStream.java:2315)
	at com.google.datastore.v1.RunQueryResponse.<init>(RunQueryResponse.java:54)
	at com.google.datastore.v1.RunQueryResponse.<init>(RunQueryResponse.java:13)
	at com.google.datastore.v1.RunQueryResponse$1.parsePartialFrom(RunQueryResponse.java:815)
	at com.google.datastore.v1.RunQueryResponse$1.parsePartialFrom(RunQueryResponse.java:810)
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:197)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:215)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:220)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.google.protobuf.GeneratedMessageV3.parseWithIOException(GeneratedMessageV3.java:293)
	at com.google.datastore.v1.RunQueryResponse.parseFrom(RunQueryResponse.java:270)
	at com.google.datastore.v1.client.Datastore.runQuery(Datastore.java:109)
	at com.google.cloud.datastore.spi.v1.HttpDatastoreRpc.runQuery(HttpDatastoreRpc.java:179)
	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:95)
	at com.google.cloud.datastore.DatastoreImpl$1.call(DatastoreImpl.java:91)
	at com.google.api.gax.retrying.DirectRetryingExecutor.submit(DirectRetryingExecutor.java:92)
	at com.google.cloud.RetryHelper.runWithRetries(RetryHelper.java:47)
	at com.google.cloud.datastore.DatastoreImpl.runQuery(DatastoreImpl.java:90)
	... 52 common frames omitted
```

Culprit remapped class:

```java
package com.google.type;

import com.google.bigtable.repackaged.com.google.protobuf.ExtensionRegistry;
import com.google.bigtable.repackaged.com.google.protobuf.ExtensionRegistryLite;
import com.google.bigtable.repackaged.com.google.protobuf.Descriptors.Descriptor;
import com.google.bigtable.repackaged.com.google.protobuf.Descriptors.FileDescriptor;
import com.google.bigtable.repackaged.com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner;
import com.google.bigtable.repackaged.com.google.protobuf.GeneratedMessageV3.FieldAccessorTable;

public final class LatLngProto {
    static final Descriptor internal_static_google_type_LatLng_descriptor;
    static final FieldAccessorTable internal_static_google_type_LatLng_fieldAccessorTable;
    private static FileDescriptor descriptor;

    private LatLngProto() {
    }

    public static void registerAllExtensions(ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(ExtensionRegistry registry) {
        registerAllExtensions((ExtensionRegistryLite)registry);
    }

    public static FileDescriptor getDescriptor() {
        return descriptor;
    }

    static {
        String[] descriptorData = new String[]{"\n\u0018google/type/latlng.proto\u0012\u000bgoogle.type\"-\n\u0006LatLng\u0012\u0010\n\blatitude\u0018\u0001 \u0001(\u0001\u0012\u0011\n\tlongitude\u0018\u0002 \u0001(\u0001B`\n\u000fcom.google.typeB\u000bLatLngProtoP\u0001Z8google.golang.org/genproto/googleapis/type/latlng;latlng¢\u0002\u0003GTPb\u0006proto3"};
        InternalDescriptorAssigner assigner = new InternalDescriptorAssigner() {
            public ExtensionRegistry assignDescriptors(FileDescriptor root) {
                LatLngProto.descriptor = root;
                return null;
            }
        };
        FileDescriptor.internalBuildGeneratedFileFrom(descriptorData, new FileDescriptor[0], assigner);
        internal_static_google_type_LatLng_descriptor = (Descriptor)getDescriptor().getMessageTypes().get(0);
        internal_static_google_type_LatLng_fieldAccessorTable = new FieldAccessorTable(internal_static_google_type_LatLng_descriptor, new String[]{"Latitude", "Longitude"});
    }
}
```

**Comment by sduskis** [comment]
In the short term, we should do a brute force approach of shading all of the following

- com/google/type/
- com/google/rpc/
- com/google/logging/
- com/google/cloud/audit/
- com/google/longrunning/

We are going to work on a better solution over the next couple of months.

**Comment by ankurcha** [comment]
Thanks. so current work around is to steer away from the 0.9.6 release?

**Comment by sduskis** [comment]
We'll deploy a 0.9.6-SNAPSHOT.  If that works for you, we can deploy a 0.9.6.1 official release with the change.  We did something like that for the 0.9.5 release.

**Comment by sduskis** [comment]
I deployed 0.9.7-SNAPSHOT (sorry for the earlier typo).

[Here](https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/master/java/hello-world/pom.xml#L41) is an example of how to setup the snapshot repo in a pom.xml file.

**Comment by ankurcha** [comment]
Thanks. Will use downscaling for now till 0.9.6.1 is out.

**Comment by sduskis** [comment]
Understood.  I'll release 0.9.6.1 first thing tomorrow.

**Comment by sduskis** [comment]
I just started the process to roll out 0.9.6.1.  It can take a few hours for the change to fully propagate across the maven repos.
