### ISSUE TITLE
NullPointerException in SerializingExecutor

### ISSUE THREAD

**Issue by jsw** [GoogleCloudPlatform/cloud-bigtable-client#1459]
Using `bigtable-hbase-1.x:1.0.0-pre1`
I don't have a repro.
I've only seen this once.

```
2017-07-13 05:13:14,912 [ERROR] [grpc-default-executor-132] [] i.g.i.SerializingExecutor:120 Exception while executing runnable io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead@71058680
java.lang.NullPointerException: null
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.onError(AbstractRetryingOperation.java:148)
	at com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.onClose(AbstractRetryingOperation.java:140)
	at com.google.cloud.bigtable.grpc.scanner.RetryingReadRowsOperation.onClose(RetryingReadRowsOperation.java:142)
	at com.google.cloud.bigtable.grpc.io.ChannelPool$InstrumentedChannel$2.onClose(ChannelPool.java:210)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:56)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor$UnAuthResponseListener.onClose(RefreshingOAuth2CredentialsInterceptor.java:416)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at io.grpc.internal.ClientCallImpl.access$100(ClientCallImpl.java:76)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:512)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:429)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessageRead.runInContext(ClientCallImpl.java:497)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:52)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by sduskis** [comment]
I've seen this sometimes in my tests.  [This PR](https://github.com/GoogleCloudPlatform/cloud-bigtable-client/pull/1442) fixes the problem.  We'll do our best to work through the other issues you've brought up, and then we'll release a `1.0.0-pre2` version.

Sorry for the trouble.
