### ISSUE TITLE
can we use 'bigtable-hbase-1.x-hadoop' in non-hadoop environment

### ISSUE THREAD

**Issue by yaojuncn** [GoogleCloudPlatform/cloud-bigtable-client#1507]
Hi, google, 

when reading this  [https://cloud.google.com/bigtable/docs/release-notes](https://cloud.google.com/bigtable/docs/release-notes)
it said: 

> The HBase client for Java now provides three Maven artifacts:

bigtable-hbase-1.x: Use this artifact for standalone applications where you control your dependencies.
bigtable-hbase-1.x-hadoop: Use this artifact for Hadoop environments.
bigtable-hbase-1.x-shaded: Use this artifact for environments other than Hadoop that require older versions of the HBase client for Java's dependencies, such as protobuf and Guava.

my question, can we use "bigtable-hbase-1.x-hadoop" in our own standalone application? 
we try to use one same version for all our apps both running standalone and in hadoop env, thx

also,  here [https://mvnrepository.com/artifact/com.google.cloud.bigtable/bigtable-hbase-1.x-hadoop/1.0.0-pre3](https://mvnrepository.com/artifact/com.google.cloud.bigtable/bigtable-hbase-1.x-hadoop/1.0.0-pre3)
it said 
> Bigtable connector compatible with HBase 1.x. It most of its dependencies (hbase & grpc). Its mainly intended to be used by dataflow 1.x to avoid version conflicts with grpc & protobuf. Prefer to use bigtable-hbase-1.x.

so is the "bigtable-hbase-1.x-hadoop" mainly to be used in dataflow 1.x? 
If we are running dataproc with spark, is using 'bigtable-hbase-1.x' a better way? 

Thanks.

**Comment by yaojuncn** [comment]
also, does the latest 'com.google.cloud.bigtable:bigtable-hbase-1.x:1.0.0-pre3' has any grpc conflicts with any other google library of previous version? 

I have other google library dependencies on datastore, bigquery, gcs of some early version, 

if this '1.0.0-pre3' requires other google library to be the latest one, it will be a huge version upgrade for us. 

or, is there a compatible matrix of across all google libraries of gcs/bigtable/bigquery/datastore/...? 

thanks

below is the exception I got after upgrading the version
>Caused by: java.lang.NoSuchMethodError: com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(Lcom/google/auth/http/HttpTransportFactory;)Lcom/google/auth/oauth2/GoogleCredentials;
	at com.google.cloud.bigtable.config.CredentialFactory.getApplicationDefaultCredential(CredentialFactory.java:217)
	at com.google.cloud.bigtable.config.CredentialFactory.getCredentials(CredentialFactory.java:121)
	at com.google.cloud.bigtable.grpc.io.CredentialInterceptorCache.getCredentialsInterceptor(CredentialInterceptorCache.java:95)
	at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:253)
	at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:143)
	at com.google.cloud.bigtable.hbase1_x.BigtableConnection.<init>(BigtableConnection.java:58)

**Comment by sduskis** [comment]
Short answer: You can definitely use the 1.x-hadoop artifact outside of hadoop, and that will be a quick fix to get you around the problem in comment 2.

The main difference between 1.x-hadoop and the 1.x artifact relates to package renaming.  The 1.x is pretty straightforward in terms of dependencies.  The 1.x-hadoop includes all of the dependencies, like the ApplicationsCredentials, in an uber-jar under relocated package names.

We don't currently have a compatibility matrix.  Can you give us a bit more info around which versions of other clients you are using?  A pom.xml would be awesome to help us find the root of the inconsistency.

**Comment by yaojuncn** [comment]
our current google related dependency 
`compile 'com.google.guava:guava:19.0'

compile ("com.google.apis:google-api-services-storage:v1-rev92-1.22.0") {
         exclude group:  'com.google.guava'
         exclude group: 'io.netty', module: 'netty-tcnative-boringssl-static'
     }
     compile ("com.google.apis:google-api-services-bigquery:v2-rev330-1.22.0") {
         exclude group:  'com.google.guava'
         exclude group: 'io.netty', module: 'netty-tcnative-boringssl-static'
   }
   
   compile ("com.google.apis:google-api-services-pubsub:v1-rev14-1.22.0") {
         exclude group:  'com.google.guava'
         exclude group: 'io.netty', module: 'netty-tcnative-boringssl-static'
   }

     compile 'com.google.http-client:google-http-client-protobuf:1.22.0'`

**Comment by igorbernstein2** [comment]
Mixing bigtable-hbase-1.x-hadoop with other google clients will create the same headaches as mixing other google clients with hadoop-client. The underlying issue is that hadoop adds old versions of protobuf & guava to your dependency tree which will break modern grpc library dependencies.

If you got the other google clients running in hadoop, then adding bigtable-hbase-1.x-hadoop should not break anything. The only caveat is that in pre3, all google clients have to use netty 4.1.8.Final and tcnative 1.1.33.Fork26. This limitation will be removed in pre4, which will shade tcnative in bigtable-hbase-1.x.-hadoop, allowing bigtable-hbase-1.x-hadoop to coexist with any version of netty.

**Comment by yaojuncn** [comment]
do you have any idea of pre4 release date?

**Comment by sduskis** [comment]
I'll aim for early next week.  We have a couple of minor touch ups for a new feature (Tracing via Google Cloud Tracing) that I'd like to complete before the release..

**Comment by yaojuncn** [comment]
try to understand @igorbernstein2 's words, it's kind of confusing to me for below two parts? 
will it break or not when I have 'bigtable-hbase-1.x-hadoop' and other google library running in both hadoop and non-hadoop env?

> Mixing bigtable-hbase-1.x-hadoop with other google clients will create the same headaches as mixing other google clients with hadoop-client. The underlying issue is that hadoop adds old versions of protobuf & guava to your dependency tree which will break modern grpc library dependencies.

>If you got the other google clients running in hadoop, then adding bigtable-hbase-1.x-hadoop should not break anything.

**Comment by igorbernstein2** [comment]
Main issue that I see in the dependencies that you listed is that
google-http-client-protobuf depends on protobuf-java 2.6.1. While bigtable-hbase-1.x-hadoop depends on hbase-client that in turn depends on protobuf-java-2.5.0. The issue lies in the version differences between hbase-client and the other google libraries and is unrelated to bigtable-hbase-1.x-hadoop.
If you've successfully solved that issue (by using google-http-client-protobuf in a hadoop environment), then there is no obvious reason why bigtable-hbase-1.x-hadoop would break your environment.

**Comment by yaojuncn** [comment]
so 'protobuf-java 2.6.1' and  'protobuf-java-2.5.0' are not compatible?

**Comment by igorbernstein2** [comment]
I'm not sure to be honest, this is something that you would need to test.  Protobuf did not adopt semantic versioning until 3.0. I know that messages compiled with protobuf 2.4 are incompatible with protobuf 2.5 runtime, and the public api for Bytestrings changed between versions 2.6 & 2.7.

Are you currently using  `com.google.http-client:google-http-client-protobuf:1.22.0` in a hadoop environment? If so, then you shouldn't have any issues.

**Comment by yaojuncn** [comment]
Thanks. I just excluded it from the hadoop env. 

do you think this two will be compatible or not? 
com.google.cloud.bigtable:bigtable-hbase-1.x:1.0.0-pre3'
com.google.http-client:google-http-client-protobuf:1.22.0

**Comment by sduskis** [comment]
I don't think so.  From [this pom.xml file](https://github.com/google/google-http-java-client/blob/dev/pom.xml#L616), it looks like  com.google.http-client:google-http-client-protobuf:1.22.0 uses protobuf 2.6.1.  You'll have to use the `bigtable-hbase-1.x-hadoop` artifact to make everything work properly.
