### ISSUE TITLE
RetriesExhaustedWithDetailsException occurs when running multiple parallel Bigtable Dataflow jobs

### ISSUE THREAD

**Issue by iros** [GoogleCloudPlatform/cloud-bigtable-client#1536]
I am running a somewhat large number of simultaneous Bigtable Dataflow jobs (~50), and am running into the following exceptions in some of them (about 10 or so). The jobs run Bigquery queries and then write them to the tables. There isn't any additional processing except converting the TableRows.

Initially, all 50 happened on the same pipeline, but I've recently attempted to parallelize that and now each creates its own Bigtable connection. They are also each spawned as threads that run in parallel. These issues were introduced in this refactoring. They also appear after running for some time (not immediately.)

Exception:
```
Caused by: com.google.cloud.dataflow.sdk.util.UserCodeException: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 25 actions: StatusRuntimeException: 25 times, servers with issues: batch-bigtable.googleapis.com, 
	at com.google.cloud.dataflow.sdk.util.UserCodeException.wrap(UserCodeException.java:35)
	at com.google.cloud.dataflow.sdk.util.UserCodeException.wrapIf(UserCodeException.java:40)
	at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.wrapUserCodeException(DoFnRunnerBase.java:369)
	at com.google.cloud.dataflow.sdk.util.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:51)
	at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.processElement(DoFnRunnerBase.java:139)
	at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:188)
	at com.google.cloud.dataflow.sdk.runners.worker.ForwardingParDoFn.processElement(ForwardingParDoFn.java:42)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerLoggingParDoFn.processElement(DataflowWorkerLoggingParDoFn.java:47)
	at com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.process(ParDoOperation.java:55)
	at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:52)
	at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:158)
	at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnContext.outputWindowedValue(DoFnRunnerBase.java:288)
	at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase$DoFnProcessContext.output(DoFnRunnerBase.java:450)
	at mlab.dataviz.dofn.TableRowToHBase.processElement(TableRowToHBase.java:122)
	at com.google.cloud.dataflow.sdk.util.SimpleDoFnRunner.invokeProcessElement(SimpleDoFnRunner.java:49)
	at com.google.cloud.dataflow.sdk.util.DoFnRunnerBase.processElement(DoFnRunnerBase.java:139)
	at com.google.cloud.dataflow.sdk.runners.worker.SimpleParDoFn.processElement(SimpleParDoFn.java:188)
	at com.google.cloud.dataflow.sdk.runners.worker.ForwardingParDoFn.processElement(ForwardingParDoFn.java:42)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerLoggingParDoFn.processElement(DataflowWorkerLoggingParDoFn.java:47)
	at com.google.cloud.dataflow.sdk.util.common.worker.ParDoOperation.process(ParDoOperation.java:55)
	at com.google.cloud.dataflow.sdk.util.common.worker.OutputReceiver.process(OutputReceiver.java:52)
	at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:221)
	at com.google.cloud.dataflow.sdk.util.common.worker.ReadOperation.start(ReadOperation.java:182)
	at com.google.cloud.dataflow.sdk.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:69)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.executeWork(DataflowWorker.java:287)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.doWork(DataflowWorker.java:220)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorker.getAndPerformWork(DataflowWorker.java:170)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.doWork(DataflowWorkerHarness.java:192)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:172)
	at com.google.cloud.dataflow.sdk.runners.worker.DataflowWorkerHarness$WorkerThread.call(DataflowWorkerHarness.java:159)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

My dependencies:

```xml
<dependency>
			<groupId>com.google.auth</groupId>
			<artifactId>google-auth-library-credentials</artifactId>
			<version>0.6.1</version>
		</dependency>

		<dependency>
			<groupId>com.google.auth</groupId>
			<artifactId>google-auth-library-oauth2-http</artifactId>
			<version>0.6.1</version>
		</dependency>

		<dependency>
			<groupId>com.google.cloud.dataflow</groupId>
			<artifactId>google-cloud-dataflow-java-sdk-all</artifactId>
			<version>1.9.1</version>
		</dependency>

		<dependency>
			<groupId>com.google.cloud.datastore</groupId>
			<artifactId>datastore-v1-protos</artifactId>
			<version>1.3.0</version>
		</dependency>

		<dependency>
			<groupId>com.google.protobuf</groupId>
			<artifactId>protobuf-java</artifactId>
			<version>3.2.0</version>
		</dependency>

		<dependency>
			<groupId>com.google.cloud</groupId>
			<artifactId>google-cloud-datastore</artifactId>
			<version>1.11.0</version>
		</dependency>

		<dependency>
			<groupId>com.google.cloud.bigtable</groupId>
			<artifactId>bigtable-hbase-dataflow</artifactId>
			<version>1.0.0-pre3</version>
		</dependency>

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>23.2-jre</version>
		</dependency>

```

Code:

```java
public class BigtablePipeline implements Runnable {
    private BigtableTransferPipelineOptions options;
    private Pipeline pipe;

public BigtablePipeline(String[] args) {
        // setup options
        PipelineOptionsFactory.register(BigtableTransferPipelineOptions.class);
        this.options = PipelineOptionsFactory.fromArgs(args).withValidation()
                .as(BigtableTransferPipelineOptions.class);
        // create pipeline
        this.pipe = Pipeline.create(this.options);
    }

 @Override
    public void run() {
        try {
            String queryString = this.getQueryString();

            LOG.info("Reading data from BigQuery query");
            // Formally called this.pipeline.apply.
            PCollection<TableRow> bigQueryCollection = pipe
                    .apply(BigQueryIO.Read.fromQuery(queryString));

            CloudBigtableIO.initializeForWrite(pipe);

            // create configuration for writing to the Bigtable
            CloudBigtableScanConfiguration config = new CloudBigtableScanConfiguration.Builder()
                    .withProjectId(this.options.getProject())
                    .withInstanceId(this.options.getInstance())
                    .withTableId(btConfig.getBigtableTable()).build();

            // convert from TableRow objects to hbase compatible mutations (Put)
            PCollection<Mutation> hbasePuts = bigQueryCollection.apply(
                    ParDo.named(this.getBigtableTable() + " BT Transform")
                    .of(new TableRowToHBase(btConfig)));

            // write the mutations to Bigtable
            hbasePuts.apply(CloudBigtableIO.writeToTable(config));

            DataflowPipelineJob result = (DataflowPipelineJob) this.pipe.run();
            try {
                result.waitToFinish(-1, TimeUnit.MINUTES, new MonitoringUtil.PrintHandler(System.out));
            } catch (InterruptedException e) {
                LOG.error(e.getMessage());
                e.printStackTrace();
            }
        } catch (IOException e) {
            LOG.error(e.getMessage());
            e.printStackTrace();
        }
    }
}
```

The source instantiating these classes does so in this way:

```java
ArrayList<Thread> threads = new ArrayList<Thread>();
for (File f : listOfFiles) {
    btPipeline = new BigtablePipeline(this.args, f.filename());
    Thread btPipeThread = new Thread(btPipeline);
    btPipeThread.start();
   threads.add(btPipeThread);
}

// once all jobs have been queued up, wait for them all
for (Thread t : threads) {
try {
    t.join();
} catch (InterruptedException ex) {
   LOG.error(ex.getMessage());
   ex.printStackTrace();
}
```

**Comment by igorbernstein2** [comment]
Hi Irene,

Can I ask you to  reproduce the issue with the recently tagged (but unreleased) 1.0.0 version of the client? sduskis recently added more logging for these types of situations

1. Install the client:
```
git clone https://github.com/GoogleCloudPlatform/cloud-bigtable-client.git
cd cloud-bigtable-client
git checkout bigtable-client-1.0.0
mvn clean install
```
2. update your project to use 1.0.0 version of the client

3. update your log4.properties to use the level DEBUG for 
com.google.cloud.bigtable.hbase.BigtableBufferedMutator


As an aside, I think you can simplify your pipeline to remove the multiple threads. pipeline.run() executes asynchronously already, so you can create & run multiple pipelines in the main thread and then iterate through them calling `waitToFinish`

**Comment by sduskis** [comment]
@igorbernstein2, 1. does not have to happen.  1.0.0 is in the repos.

**Comment by sduskis** [comment]
iros@, can you please open a support ticket?  We'll likely need your projectId and instanceID,
which would have to come through the support process.  (**please don't paste them here**)

**Comment by sduskis** [comment]
I didn't see much on this.  I'm going to close this.
