### ISSUE TITLE
java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN

### ISSUE THREAD

**Issue by jsw** [GoogleCloudPlatform/cloud-bigtable-client#1549]
What's the magic set of dependencies I need to align to remove this runtime error?

```
[info] java.lang.IllegalStateException: Could not find an appropriate constructor for com.google.cloud.bigtable.hbase1_x.BigtableConnection
[info]   at com.google.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:114)
[info]   at com.google.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:99)
...
[info]   Cause: java.lang.reflect.InvocationTargetException:
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at com.google.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:111)
[info]   at com.google.cloud.bigtable.hbase.BigtableConfiguration.connect(BigtableConfiguration.java:99)
...
[info]   Cause: java.lang.IllegalArgumentException: Jetty ALPN/NPN has not been properly configured.
[info]   at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:162)
[info]   at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
[info]   at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)
[info]   at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
[info]   at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:521)
[info]   at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:514)
[info]   at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:453)
[info]   at io.grpc.netty.NettyChannelBuilder.buildTransportFactory(NettyChannelBuilder.java:312)
[info]   at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:324)
[info]   at com.google.cloud.bigtable.grpc.BigtableSession.createNettyChannel(BigtableSession.java:483)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: org/eclipse/jetty/alpn/ALPN
[info]   at java.lang.Class.forName0(Native Method)
[info]   at java.lang.Class.forName(Class.java:348)
[info]   at io.grpc.netty.JettyTlsUtil.isJettyAlpnConfigured(JettyTlsUtil.java:34)
[info]   at io.grpc.netty.GrpcSslContexts.selectApplicationProtocolConfig(GrpcSslContexts.java:153)
[info]   at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:136)
[info]   at io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:124)
[info]   at io.grpc.netty.GrpcSslContexts.forClient(GrpcSslContexts.java:94)
[info]   at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:521)
[info]   at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory$DefaultNettyTransportCreationParamsFilterFactory.<init>(NettyChannelBuilder.java:514)
[info]   at io.grpc.netty.NettyChannelBuilder$NettyTransportFactory.<init>(NettyChannelBuilder.java:453)
```

Relevant dependencies:
```
sbt dependencyList | egrep "netty|grpc|bigtable"
[info] com.google.api:gax-grpc:0.22.0
[info] com.google.api.grpc:grpc-google-cloud-pubsub-v1:0.1.14
[info] com.google.api.grpc:grpc-google-common-protos:0.1.9
[info] com.google.api.grpc:proto-google-cloud-pubsub-v1:0.1.14
[info] com.google.api.grpc:proto-google-common-protos:1.0.1
[info] com.google.api.grpc:proto-google-iam-v1:0.1.25
[info] com.google.cloud:google-cloud-core-grpc:1.3.0
[info] com.google.cloud.bigtable:bigtable-client-core:1.0.0
[info] com.google.cloud.bigtable:bigtable-hbase:1.0.0
[info] com.google.cloud.bigtable:bigtable-hbase-1.x:1.0.0
[info] com.google.cloud.bigtable:bigtable-protos:1.0.0
[info] com.trueaccord.scalapb:scalapb-runtime-grpc_2.12:0.6.7
[info] com.typesafe.play:play-netty-utils:2.6.7
[info] io.grpc:grpc-auth:1.7.0
[info] io.grpc:grpc-context:1.7.0
[info] io.grpc:grpc-core:1.7.0
[info] io.grpc:grpc-netty:1.7.0
[info] io.grpc:grpc-protobuf:1.7.0
[info] io.grpc:grpc-protobuf-lite:1.7.0
[info] io.grpc:grpc-stub:1.7.0
[info] io.netty:netty-buffer:4.1.16.Final
[info] io.netty:netty-codec:4.1.16.Final
[info] io.netty:netty-codec-http:4.1.16.Final
[info] io.netty:netty-codec-http2:4.1.16.Final
[info] io.netty:netty-codec-socks:4.1.16.Final
[info] io.netty:netty-common:4.1.16.Final
[info] io.netty:netty-handler:4.1.16.Final
[info] io.netty:netty-handler-proxy:4.1.16.Final
[info] io.netty:netty-resolver:4.1.16.Final
[info] io.netty:netty-tcnative-boringssl-static:2.0.3.Final
[info] io.netty:netty-transport:4.1.16.Final
[info] io.opencensus:opencensus-contrib-grpc-util:0.7.0
```

**Comment by sduskis** [comment]
this is the problem: 
`io.netty:netty-tcnative-boringssl-static:2.0.3.Final`

use this dependency explicitly:

`io.netty:netty-tcnative-boringssl-static:2.0.6.Final`

Alternatively, upgrade your pub-sub dependency to the latest version.

You've hit what we call the "diamond dependency problem" aka DLL Hell.  Including 2 Google Cloud clients (or really any two grpc based libraries that use different versions of grpc) could have this problem.

tcnative 2.0.6 and and 2.0.3 are not binary compatible.  Cloud Bigtable 1.0.0 uses grpc 1.7.0 uses grpc 1.7.0 which in turn goes well with tcnative 2.0.6.  Newer pubsub dependencies also use grpc 1.7.0

**Comment by jsw** [comment]
@sduskis Thanks! Upgrading `google-cloud-pubsub` to latest is exactly what was needed to get tcnative up to 2.0.6. Not sure why sbt chose 2.0.3 over 2.0.6, though.
