### ISSUE TITLE
bigtable-beam-import 1.1.0 jar

### ISSUE THREAD

**Issue by rlucioni** [GoogleCloudPlatform/cloud-bigtable-client#1638]
Congratulations on releasing 1.1.0! Are there plans to make a 1.1.0 bigtable-beam-import jar available? The latest at http://repo1.maven.org/maven2/com/google/cloud/bigtable/bigtable-beam-import/ appears to be 1.0.0. Thank you!

**Comment by sduskis** [comment]
I thought I hit the `Release` button earlier in Sonatype, earlier today, but I guess not.  I just pushed it, so hopefully maven should distribute the artifacts over the next few hours.

**Comment by sduskis** [comment]
I just checked repo1, and 1.1.0 was rolled out.  [Here's the direct link for the shaded import jar](http://repo1.maven.org/maven2/com/google/cloud/bigtable/bigtable-beam-import/1.1.0/bigtable-beam-import-1.1.0-shaded.jar).

**Comment by rlucioni** [comment]
Great! Thank you for the quick response.

**Comment by InfyNord** [comment]
I am getting below error  error . any idea what is issue
 2018-05-23 19:54:55 INFO  MonitoringUtil$LoggingHandler:108 - 2018-05-23T19:54:54.478Z: Workers have started successfully.
2018-05-23 19:55:15 ERROR MonitoringUtil$LoggingHandler:101 - 2018-05-23T19:55:14.257Z: org.apache.hadoop.hbase.client.RetriesExhaustedWithDetailsException: Failed 125 actions: StatusRuntimeException: 125 times,
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.handleExceptions(BigtableBufferedMutator.java:276)
        at com.google.cloud.bigtable.hbase.BigtableBufferedMutator.mutate(BigtableBufferedMutator.java:199)
        at com.google.cloud.bigtable.beam.CloudBigtableIO$CloudBigtableSingleTableBufferedWriteFn.processElement(CloudBigtableIO.java:875)

**Comment by sduskis** [comment]
@InfyNord: It's difficult to tell without more information.  I think that the best way forward would be to open a support ticket.
