### ISSUE TITLE
DropWizard dependency issue on 1.x:1.5.0

### ISSUE THREAD

**Issue by KaoruDev** [GoogleCloudPlatform/cloud-bigtable-client#1915]
Similar to this issue: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/1224

Except I'm trying to use:

```
compile('com.google.cloud.bigtable:bigtable-hbase-1.x:1.5.0')
```

when I set gradle to ignore transitive dependencies, 

```gradle
compile('com.google.cloud.bigtable:bigtable-hbase-1.x:1.5.0') {
  transitive = false
}
```

Intellij complains that it cannot find `com.google.cloud.bigtable.hbase.BigtableConfiguration`. Behavior also occurs when I use the shaded versions.

Error:

```
ERROR [2018-08-23 20:40:15,275] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.lang.NullPointerException: null
! at com.sun.jersey.core.provider.jaxb.AbstractJAXBProvider.setConfiguration(AbstractJAXBProvider.java:109) ~[hbase-shaded-client-1.2.0-cdh5.11.1.jar:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
! at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
! at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1041) ~[hk2-utils-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.ClazzCreator.methodMe(ClazzCreator.java:321) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:374) ~[hk2-locator-2.4.0-b25.jar:na]
! ... 89 common frames omitted
! Causing: org.glassfish.hk2.api.MultiException: A MultiException has 3 exceptions.  They are:
! 1. java.lang.NullPointerException
! 2. java.lang.IllegalStateException: Unable to perform operation: method inject on com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$App
! 3. java.lang.IllegalStateException: Unable to perform operation: create on org.glassfish.jersey.message.internal.MessageBodyFactory
! 
! at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:394) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:470) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:69) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2065) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:105) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:87) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.glassfish.jersey.internal.inject.ProviderToService.apply(ProviderToService.java:58) ~[jersey-common-2.19.jar:na]
! at org.glassfish.jersey.internal.inject.ProviderToService.apply(ProviderToService.java:54) ~[jersey-common-2.19.jar:na]
! at jersey.repackaged.com.google.common.collect.Iterators$8.transform(Iterators.java:799) ~[jersey-guava-2.19.jar:na]
! at jersey.repackaged.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48) ~[jersey-guava-2.19.jar:na]
! at java.util.AbstractCollection.addAll(AbstractCollection.java:343) ~[na:1.8.0_144]
! at java.util.LinkedHashSet.<init>(LinkedHashSet.java:169) ~[na:1.8.0_144]
! at jersey.repackaged.com.google.common.collect.Sets.newLinkedHashSet(Sets.java:325) ~[jersey-guava-2.19.jar:na]
! at org.glassfish.jersey.internal.inject.Providers.getClasses(Providers.java:392) ~[jersey-common-2.19.jar:na]
! at org.glassfish.jersey.internal.inject.Providers.getProviders(Providers.java:188) ~[jersey-common-2.19.jar:na]
! at org.glassfish.jersey.message.internal.MessageBodyFactory.<init>(MessageBodyFactory.java:222) ~[jersey-common-2.19.jar:na]
! at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_144]
! at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_144]
! at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_144]
! at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_144]
! at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1129) ~[hk2-utils-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:274) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:368) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:470) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:82) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:70) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97) ~[hk2-utils-2.4.0-b25.jar:na]
! at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_144]
! at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154) ~[hk2-utils-2.4.0-b25.jar:na]
! at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199) ~[hk2-utils-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:121) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2065) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:761) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:700) ~[hk2-locator-2.4.0-b25.jar:na]
! at org.glassfish.jersey.server.model.ComponentModelValidator.<init>(ComponentModelValidator.java:97) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:548) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:183) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:349) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:346) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[jersey-common-2.19.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[jersey-common-2.19.jar:na]
! at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255) ~[jersey-common-2.19.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:346) ~[jersey-server-2.19.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:339) ~[jersey-container-servlet-core-2.19.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:170) ~[jersey-container-servlet-core-2.19.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:362) ~[jersey-container-servlet-core-2.19.jar:na]
! at javax.servlet.GenericServlet.init(GenericServlet.java:241) ~[hbase-shaded-client-1.2.0-cdh5.11.1.jar:na]
! at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612) ~[jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! ... 42 common frames omitted
```

**Comment by sduskis** [comment]
You should probably exclude our version of `io.dropwizard.metrics:metrics-core`.  I hope that helps, but I'm not sure if it will.

**Comment by KaoruDev** [comment]
I tried this in my gradle file:

```gradle
  compile(group: 'com.google.cloud.bigtable', name: 'bigtable-hbase-1.x-shaded', version: '1.5.0') {
    exclude group: "io.dropwizard.metrics"
  }
```

with no luck, sorry my gradle isn't as good as it should be, I'll level up and report back if I find anything. Otherwise we might be stuck using the `0.9.5.1` version.

**Comment by sduskis** [comment]
Ugh.  Sorry about that.

I just saw this: `hbase-shaded-client-1.2.0-cdh5.11.1.jar`.  We use `hbase-shaded-client-1.4.*`.  You may need to exclude our `hbase-shaded-client` dependency to make this work.  Dependency management is difficult in cases like this.

**Comment by KaoruDev** [comment]
The code gods showed mercy:

```gradle
  compile('com.google.cloud.bigtable:bigtable-hbase-1.x-shaded:1.5.0') {
    transitive = false
  }
```

for some reason (my guess is incorrect caching on Intellij or somewhere on my machine) is now working perfectly. Gonna close this one out, thank you @sduskis for your help!
