### ISSUE TITLE
Prevent client from logging

### ISSUE THREAD

**Issue by KaoruDev** [GoogleCloudPlatform/cloud-bigtable-client#1916]
Is there a way to prevent the client from logging? I want to conditionally log errors thrown by the client when they arise. 

I.e these:

```
ERROR [2018-08-25 22:45:18,265] com.google.cloud.bigtable.hbase.AbstractBigtableTable: Encountered exception when executing put.
! com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: NOT_FOUND: Table not found: <omitted-url-to-table>
! at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:517) ~[bigtable-hbase-1.x-shaded-1.5.0.jar:na]
! at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.async.AbstractRetryingOperation.getBlockingResult(AbstractRetryingOperation.java:474) ~[bigtable-hbase-1.x-shaded-1.5.0.jar:na]
! at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.mutateRow(BigtableDataGrpcClient.java:236) ~[bigtable-hbase-1.x-shaded-1.5.0.jar:na]
! at com.google.cloud.bigtable.hbase.AbstractBigtableTable.put(AbstractBigtableTable.java:348) ~[bigtable-hbase-1.x-shaded-1.5.0.jar:na]
! at com.sift.db.bigtableloadtest.BigtableMirror.lambda$put$11(BigtableMirror.java:321) [classes/:na]
```

I know that the table is missing and this is actually not an error and is intentional.

Thanks!

**Comment by sduskis** [comment]
Can you do this in Log4j settings?

**Comment by KaoruDev** [comment]
Yeah, I tried, but perhaps I'm doing it wrong in our setup, I'm gonna close this until I have more confidence I'm setting things up correctly.
