### ISSUE TITLE
ResultScanner iterator (and spliterator) throws at the end of the result set

### ISSUE THREAD

**Issue by bnordli** [GoogleCloudPlatform/cloud-bigtable-client#1976]
When using the iterator of a `ResultScanner`, an `IllegalStateException` exception is encountered when calling `hasNext` the second time at the end of the result set:

## Actual behaviour
```java
Iterator<Result> iterator = connection.getTable(table).getScanner(new Scan()).iterator();
while (iterator.hasNext()) {
  iterator.next();
}
iterator.hasNext();  // throws IllegalStateException
```
Stack trace:
```
java.lang.IllegalStateException: Scanner is already closed

	at com.google.bigtable.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:75)
	at com.google.bigtable.repackaged.com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:35)
	at com.google.cloud.bigtable.hbase.adapters.read.BigtableResultScannerAdapter$1.next(BigtableResultScannerAdapter.java:66)
	at org.apache.hadoop.hbase.client.ResultScanner$1.hasNext(ResultScanner.java:53)
```

## Expected behaviour
The last line should return `false` instead of throwing an exception.

## Version

```
<dependency>
  <groupId>com.google.cloud.bigtable</groupId>
  <artifactId>bigtable-hbase-2.x-shaded</artifactId>
  <version>1.6.0</version>
</dependency>
```

**Comment by sduskis** [comment]
We fixed this in #2087, which was part of the 1.9.0 release.
