### ISSUE TITLE
bigtable-beam-import does not run in Java11

### ISSUE THREAD

**Issue by ramonmedeiros** [GoogleCloudPlatform/cloud-bigtable-client#2041]
We tried to run the beam-import in java11 and got issues:

```
[12:22:49]  2019-01-07 12:22:48 INFO  DataflowPipelineOptions$StagingLocationFactory:142 - No stagingLocation provided, falling back to gcpTempLocation
[12:22:49]  Exception in thread "main" java.lang.RuntimeException: Failed to construct instance from factory method DataflowRunner#fromOptions(interface org.apache.beam.sdk.options.PipelineOptions)
[12:22:49]  	at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:233)
[12:22:49]  	at org.apache.beam.sdk.util.InstanceBuilder.build(InstanceBuilder.java:162)
[12:22:49]  	at org.apache.beam.sdk.PipelineRunner.fromOptions(PipelineRunner.java:55)
[12:22:49]  	at org.apache.beam.sdk.Pipeline.create(Pipeline.java:150)
[12:22:49]  	at com.google.cloud.bigtable.beam.sequencefiles.ExportJob.buildPipeline(ExportJob.java:200)
[12:22:49]  	at com.google.cloud.bigtable.beam.sequencefiles.ExportJob.main(ExportJob.java:171)
[12:22:49]  	at com.google.cloud.bigtable.beam.sequencefiles.Main.main(Main.java:38)
[12:22:49]  Caused by: java.lang.reflect.InvocationTargetException
[12:22:49]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:22:49]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:22:49]  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:22:49]  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[12:22:49]  	at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:222)
[12:22:49]  	... 6 more
[12:22:49]  Caused by: java.lang.IllegalArgumentException: Unable to use ClassLoader to detect classpath elements. Current ClassLoader is jdk.internal.loader.ClassLoaders$AppClassLoader@799f7e29, only URLClassLoaders are supported.
[12:22:49]  	at org.apache.beam.runners.core.construction.PipelineResources.detectClassPathResourcesToStage(PipelineResources.java:43)
[12:22:49]  	at org.apache.beam.runners.dataflow.DataflowRunner.fromOptions(DataflowRunner.java:261)
[12:22:49]  	... 11 more
[12:22:49]  [2019-01-07 12:22:48] WARNING process.py:30:exec() - will retry for command (export table (video)), on try: 0
[12:23:21]  2019-01-07 12:23:15 INFO  DataflowPipelineOptions$StagingLocationFactory:142 - No stagingLocation provided, falling back to gcpTempLocation
[12:23:21]  Exception in thread "main" java.lang.RuntimeException: Failed to construct instance from factory method DataflowRunner#fromOptions(interface org.apache.beam.sdk.options.PipelineOptions)
[12:23:21]  	at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:233)
[12:23:21]  	at org.apache.beam.sdk.util.InstanceBuilder.build(InstanceBuilder.java:162)
[12:23:21]  	at org.apache.beam.sdk.PipelineRunner.fromOptions(PipelineRunner.java:55)
[12:23:21]  	at org.apache.beam.sdk.Pipeline.create(Pipeline.java:150)
[12:23:21]  	at com.google.cloud.bigtable.beam.sequencefiles.ExportJob.buildPipeline(ExportJob.java:200)
[12:23:21]  	at com.google.cloud.bigtable.beam.sequencefiles.ExportJob.main(ExportJob.java:171)
[12:23:21]  	at com.google.cloud.bigtable.beam.sequencefiles.Main.main(Main.java:38)
[12:23:21]  Caused by: java.lang.reflect.InvocationTargetException
[12:23:21]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[12:23:21]  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[12:23:21]  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[12:23:21]  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[12:23:21]  	at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:222)
[12:23:21]  	... 6 more
[12:23:21]  Caused by: java.lang.IllegalArgumentException: Unable to use ClassLoader to detect classpath elements. Current ClassLoader is jdk.internal.loader.ClassLoaders$AppClassLoader@799f7e29, only URLClassLoaders are supported.
[12:23:21]  	at org.apache.beam.runners.core.construction.PipelineResources.detectClassPathResourcesToStage(PipelineResources.java:43)
[12:23:21]  	at org.apache.beam.runners.dataflow.DataflowRunner.fromOptions(DataflowRunner.java:261)
[12:23:21]  	... 11 more
```

Do you guys plan to support Java11? For me, java8 works fine

**Comment by sduskis** [comment]
The Cloud Bigtable import process uses on [Apache Beam](https://beam.apache.org/).  The issue you're seeing relates to Apache Beam rather that Cloud Bigtable.  Java 11 is on their roadmap (see [here](https://beam.apache.org/roadmap/java-sdk/)).

There isn't much we can do in this github repository, so I'm going to close this issue.
