### ISSUE TITLE
BigtableSession deadlocks when given a thread pool smaller than 3

### ISSUE THREAD

**Issue by udoprog** [GoogleCloudPlatform/cloud-bigtable-client#392]
BigtableSession currently deadlocks when given a thread pool with less than 3 available live threads.

I can always reproduce this.

## Test Case

```java
public class BigtableSessionTest {
    public static void main(String[] args) throws Exception {
        CredentialOptions credentials = /* .. */;
        final MySession session = /* .. */;

        final ExecutorService tasks = Executors.newFixedThreadPool(1);

        for (int count = 1; count <= 8; count++) {
            final ExecutorService executorService = Executors.newFixedThreadPool(count);
            final CountDownLatch latch = new CountDownLatch(1);

            final AtomicReference<Throwable> errored = new AtomicReference<Throwable>();

            // thread that builds and closes the BigtableSession...
            final Thread thread = new Thread() {
                public void run() {
                    try {
                        session.build(executorService).close();
                    } catch (Exception e) {
                        errored.set(e);
                    }

                    latch.countDown();
                };
            };

            System.out.println(String.format("%d: starting...", count));
            thread.start();

            if (!latch.await(1, TimeUnit.SECONDS)) {
                System.out.println(String.format("%d: seems to have deadlocked :(", count));
                thread.interrupt();
            }

            // wait one more time in case of deadlock...
            if (!latch.await(1, TimeUnit.SECONDS)) {
                System.out.println(String.format("%d: did not recover, exiting D:", count));
                break;
            }

            if (errored.get() != null) {
                System.out.println(String.format("%d: Task failed:", count));
                errored.get().printStackTrace(System.out);
            } else {
                System.out.println(String.format("%d: Task OK", count));
            }
        }

        System.out.println("bye, bye");
        System.exit(0);
    }

    static class MySession {
        public static final String USER_AGENT = "test";

        final String project;
        final String zone;
        final String cluster;
        final CredentialOptions credentials;

        public MySession(final String project, final String zone, final String cluster, CredentialOptions credentials) {
            this.project = project;
            this.zone = zone;
            this.cluster = cluster;
            this.credentials = credentials;
        }

        public BigtableSession build(final ExecutorService executorService) throws IOException {
            final BigtableOptions options = new BigtableOptions.Builder().setProjectId(project).setZoneId(zone)
                    .setClusterId(cluster).setUserAgent(USER_AGENT).setCredentialOptions(credentials).build();

            return new BigtableSession(options, executorService);
        }
    }
}
```

## Output

```
1: starting...
Aug 07, 2015 6:04:24 PM com.google.cloud.bigtable.config.Logger info
INFO: Opening connection for ...
1: seems to have deadlocked :(
1: Task failed:
java.io.IOException: Could not initialize the data API client
	at com.google.cloud.bigtable.grpc.BigtableSession.get(BigtableSession.java:352)
	at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:300)
	at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:252)
	at com.spotify.bigtable.BigtableSessionTest$MySession.build(BigtableSessionTest.java:89)
	at com.spotify.bigtable.BigtableSessionTest$1.run(BigtableSessionTest.java:37)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.google.cloud.bigtable.grpc.BigtableSession.get(BigtableSession.java:350)
	... 4 more
2: starting...
Aug 07, 2015 6:04:25 PM com.google.cloud.bigtable.config.Logger info
INFO: Opening connection for ...
2: seems to have deadlocked :(
2: Task failed:
java.io.IOException: Could not initialize the data API client
	at com.google.cloud.bigtable.grpc.BigtableSession.get(BigtableSession.java:352)
	at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:300)
	at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:252)
	at com.spotify.bigtable.BigtableSessionTest$MySession.build(BigtableSessionTest.java:89)
	at com.spotify.bigtable.BigtableSessionTest$1.run(BigtableSessionTest.java:37)
Caused by: java.lang.InterruptedException
	at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:404)
	at java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.google.cloud.bigtable.grpc.BigtableSession.get(BigtableSession.java:350)
	... 4 more
3: starting...
Aug 07, 2015 6:04:26 PM com.google.cloud.bigtable.config.Logger info
INFO: Opening connection for ...
3: Task OK
4: starting...
Aug 07, 2015 6:04:26 PM com.google.cloud.bigtable.config.Logger info
INFO: Opening connection for ...
4: Task OK
5: starting...
Aug 07, 2015 6:04:26 PM com.google.cloud.bigtable.config.Logger info
INFO: Opening connection for ...
5: Task OK
6: starting...
Aug 07, 2015 6:04:26 PM com.google.cloud.bigtable.config.Logger info
INFO: Opening connection for ...
6: Task OK
7: starting...
Aug 07, 2015 6:04:26 PM com.google.cloud.bigtable.config.Logger info
INFO: Opening connection for ...
7: Task OK
8: starting...
Aug 07, 2015 6:04:26 PM com.google.cloud.bigtable.config.Logger info
INFO: Opening connection for ...
8: Task OK
bye, bye
```

**Comment by sduskis** [comment]
This should be fixed.
