### ISSUE TITLE
StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence

### ISSUE THREAD

**Issue by reagere** [GoogleCloudPlatform/cloud-bigtable-client#407]
Hello,

I launch a scan on a column family of a million cells.

I have this error:
août 18, 2015 3:21:15 PM io.grpc.SerializingExecutor$TaskRunner run
GRAVE: Exception while executing runnable io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$2@6965a9c6
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
   at io.grpc.Status.asRuntimeException(Status.java:428)
   at io.grpc.protobuf.ProtoUtils$1.parse(ProtoUtils.java:64)
   at io.grpc.protobuf.ProtoUtils$1.parse(ProtoUtils.java:52)
   at io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:105)
   at io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$2.run(ChannelImpl.java:384)
   at io.grpc.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.bigtable.repackaged.com.google.protobuf.InvalidProtocolBufferException: Protocol message was too large.  May be malicious.  Use CodedInputStream.setSizeLimit() to increase the size limit.
   at com.google.bigtable.repackaged.com.google.protobuf.InvalidProtocolBufferException.sizeLimitExceeded(InvalidProtocolBufferException.java:110)
   at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.tryRefillBuffer(CodedInputStream.java:1131)
   at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:1081)
   at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.ensureAvailable(CodedInputStream.java:1068)
   at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readRawBytesSlowPath(CodedInputStream.java:1203)
   at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readBytes(CodedInputStream.java:517)
   at com.google.bigtable.v1.Column.<init>(Column.java:52)
   at com.google.bigtable.v1.Column.<init>(Column.java:13)
   at com.google.bigtable.v1.Column$1.parsePartialFrom(Column.java:822)
   at com.google.bigtable.v1.Column$1.parsePartialFrom(Column.java:816)
   at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
   at com.google.bigtable.v1.Family.<init>(Family.java:61)
   at com.google.bigtable.v1.Family.<init>(Family.java:13)
   at com.google.bigtable.v1.Family$1.parsePartialFrom(Family.java:923)
   at com.google.bigtable.v1.Family$1.parsePartialFrom(Family.java:917)
   at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
   at com.google.bigtable.v1.ReadRowsResponse$Chunk.<init>(ReadRowsResponse.java:185)
   at com.google.bigtable.v1.ReadRowsResponse$Chunk.<init>(ReadRowsResponse.java:145)
   at com.google.bigtable.v1.ReadRowsResponse$Chunk$1.parsePartialFrom(ReadRowsResponse.java:904)
   at com.google.bigtable.v1.ReadRowsResponse$Chunk$1.parsePartialFrom(ReadRowsResponse.java:898)
   at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
   at com.google.bigtable.v1.ReadRowsResponse.<init>(ReadRowsResponse.java:60)
   at com.google.bigtable.v1.ReadRowsResponse.<init>(ReadRowsResponse.java:13)
   at com.google.bigtable.v1.ReadRowsResponse$1.parsePartialFrom(ReadRowsResponse.java:1651)
   at com.google.bigtable.v1.ReadRowsResponse$1.parsePartialFrom(ReadRowsResponse.java:1645)
   at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:192)
   at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
   at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:215)
   at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
   at io.grpc.protobuf.ProtoUtils$1.parse(ProtoUtils.java:61)
   ... 7 more

**Comment by sduskis** [comment]
A million cells?  wow!  I'll take a look to see where CodedInputStream.setSizeLimit() needs to be used.  I added a bug on the grpc issue tracker to help out with this issue as well: https://github.com/grpc/grpc-java/issues/831

**Comment by reagere** [comment]
Thank you.

I have updated to version 0.2.0 and bigtable 1.1.1.

The result is now different.

Is there a streaming mode? I set ``` scan.setLoadColumnFamiliesOnDemand(true); ``` but it doesn't look like a streaming mode.

```
com.google.cloud.bigtable.grpc.scanner.ScanTimeoutException: Timeout while merging responses.
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner$ResponseQueueReader.getNextMergedRow(StreamingBigtableResultScanner.java:158)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:227)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:37)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:86)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:41)
	at com.google.cloud.bigtable.hbase.adapters.BigtableResultScannerAdapter$1.next(BigtableResultScannerAdapter.java:43)
	at com.accengage.globulus.test.bigtable.BenchMultipleColumnPrefixFilter.bench(BenchMultipleColumnPrefixFilter.java:42)
	at com.accengage.globulus.test.bigtable.BenchMultipleColumnPrefixFilter.test(BenchMultipleColumnPrefixFilter.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
[WARN] 01-09-2015 15:24:06,120 com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner backOffAndRetry - RetriesExhausted: 
com.google.cloud.bigtable.grpc.scanner.ScanTimeoutException: Timeout while merging responses.
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner$ResponseQueueReader.getNextMergedRow(StreamingBigtableResultScanner.java:158)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:227)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:37)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:86)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:41)
	at com.google.cloud.bigtable.hbase.adapters.BigtableResultScannerAdapter$1.next(BigtableResultScannerAdapter.java:43)
	at com.accengage.globulus.test.bigtable.BenchMultipleColumnPrefixFilter.bench(BenchMultipleColumnPrefixFilter.java:42)
	at com.accengage.globulus.test.bigtable.BenchMultipleColumnPrefixFilter.test(BenchMultipleColumnPrefixFilter.java:99)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

```

**Comment by kevinsi4508** [comment]
Can you confirm this doesn't happen with smaller rows with less cells?
It seems we are currently not setting partial row timeout. It is using default of 60 seconds.

**Comment by reagere** [comment]
Hello,

My data is one row (a test) with 2 columns families representing timeseries.

It is working for 1,2M cells inside one row. (600k in 2 column families)
(1200000 in 40233ms)

ok for 1.4 M too

then it breaks.

More, in less than 60 s
0 in 58416ms

If I understand, I need to do 2 requests with a split. There is not ability to stream bigger result?

```
GRAVE: Exception while executing runnable io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$2@4260722b
io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.Status.asRuntimeException(Status.java:428)
	at io.grpc.protobuf.ProtoUtils$1.parse(ProtoUtils.java:64)
	at io.grpc.protobuf.ProtoUtils$1.parse(ProtoUtils.java:52)
	at io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:105)
	at io.grpc.ChannelImpl$CallImpl$ClientStreamListenerImpl$2.run(ChannelImpl.java:384)
	at io.grpc.SerializingExecutor$TaskRunner.run(SerializingExecutor.java:154)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.bigtable.repackaged.com.google.protobuf.InvalidProtocolBufferException: Protocol message was too large.  May be malicious.  Use CodedInputStream.setSizeLimit() to increase the size limit.
	at com.google.bigtable.repackaged.com.google.protobuf.InvalidProtocolBufferException.sizeLimitExceeded(InvalidProtocolBufferException.java:110)
	at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.tryRefillBuffer(CodedInputStream.java:1131)
	at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.refillBuffer(CodedInputStream.java:1081)
	at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.ensureAvailable(CodedInputStream.java:1068)
	at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readRawBytesSlowPath(CodedInputStream.java:1203)
	at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readBytes(CodedInputStream.java:517)
	at com.google.bigtable.v1.Column.<init>(Column.java:52)
	at com.google.bigtable.v1.Column.<init>(Column.java:13)
	at com.google.bigtable.v1.Column$1.parsePartialFrom(Column.java:822)
	at com.google.bigtable.v1.Column$1.parsePartialFrom(Column.java:816)
	at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at com.google.bigtable.v1.Family.<init>(Family.java:61)
	at com.google.bigtable.v1.Family.<init>(Family.java:13)
	at com.google.bigtable.v1.Family$1.parsePartialFrom(Family.java:923)
	at com.google.bigtable.v1.Family$1.parsePartialFrom(Family.java:917)
	at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at com.google.bigtable.v1.ReadRowsResponse$Chunk.<init>(ReadRowsResponse.java:185)
	at com.google.bigtable.v1.ReadRowsResponse$Chunk.<init>(ReadRowsResponse.java:145)
	at com.google.bigtable.v1.ReadRowsResponse$Chunk$1.parsePartialFrom(ReadRowsResponse.java:904)
	at com.google.bigtable.v1.ReadRowsResponse$Chunk$1.parsePartialFrom(ReadRowsResponse.java:898)
	at com.google.bigtable.repackaged.com.google.protobuf.CodedInputStream.readMessage(CodedInputStream.java:495)
	at com.google.bigtable.v1.ReadRowsResponse.<init>(ReadRowsResponse.java:60)
	at com.google.bigtable.v1.ReadRowsResponse.<init>(ReadRowsResponse.java:13)
	at com.google.bigtable.v1.ReadRowsResponse$1.parsePartialFrom(ReadRowsResponse.java:1651)
	at com.google.bigtable.v1.ReadRowsResponse$1.parsePartialFrom(ReadRowsResponse.java:1645)
	at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:192)
	at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:215)
	at com.google.bigtable.repackaged.com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at io.grpc.protobuf.ProtoUtils$1.parse(ProtoUtils.java:61)
	... 7 more
```

**Comment by kevinsi4508** [comment]
There are two problems I can see here:
1. Proto message size limit problem.
  The fix is in a newer version of gRpc. I will confirm the fix.

2. Timeout when reading proto message.
  The timeout issue may come up with or without proto message size limit fix, will provide a way to increase that limit.

New issues opened: 
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/448
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/issues/449

**Comment by kevinsi4508** [comment]
Update on message size limit fix verification:
With the latest code in gRPC (0.9.0+). I was able to successfully tested following: 
1. Add 1.2 million cells in a row (in two column families)
2. The total row size of 74MB (the original size limit is 64MB)

I will test a bit more by increasing the size to 100MB and then 300MB.
Notice that without gRPC fix, I got the same error: "Protocol message was too large.".

**Comment by kevinsi4508** [comment]
I doubled the load to 2.4 million cells with size of 148 MB. I hit the another size limit.
INTERNAL: Frame size 155458981 exceeds maximum: 104857600

I will inform gRPC and see if the frame size limit can be removed. Again, didn't see (60 seconds) timeout issue. The timeout issue may be result of flaky connection.

**Comment by kevinsi4508** [comment]
https://github.com/grpc/grpc-java/issues/917

**Comment by kevinsi4508** [comment]
Increased maxMessageSize to 300MB (this change is not yet committed), no problem with 2.4 million cells per row with size of 148 MB.

Moving on to 4.8 million cells and this should hit the server limit.

**Comment by kevinsi4508** [comment]
Finally, I hit the timeout merging row (as expected). I will increase the timeout.

com.google.cloud.bigtable.grpc.scanner.ScanTimeoutException: Timeout while merging responses.
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner$ResponseQueueReader.getNextMergedRow(StreamingBigtableResultScanner.java:67)

**Comment by kevinsi4508** [comment]
With 2.4 millions cells, everything is fine.
With 4.8 millions cells, it hit all kind of limits, so not recommended. I would max it out at 200MB per row.
I am going to close this issue. Please make sure to have following when you want to have millions of cells in a row:

1. Set min and max versions (if manually setting versions)
   descriptor.addFamily(
          new HColumnDescriptor("bigFamily1").setMinVersions(0).setMaxVersions(999999999));

2. Set max version when doing scan
    scan.setMaxVersions(999999999);

3. Set partial read timeout to 10 minutes if get a partial read timeout
    google.bigtable.grpc.read.partial.row.timeout.ms

4. Need change in gRPC 0.9.0 or higher

5. Set Netty Channel to more than 100MB (currently is using default value of 100MB). (** I will to update it to match server limit

**Comment by sduskis** [comment]
FWIW, gRPC 0.9.0 isn't out yet.  We used a development version of gRPC to make this work.

**Comment by yaitskov** [comment]
I get this exception on counting 26 million rows in table. Table is pretty narrow (30 columns).
Version 0.2.2
```
com.google.cloud.bigtable.grpc.scanner.ScanTimeoutException: Timeout while merging responses.
	at com.google.cloud.bigtable.grpc.scanner.ResponseQueueReader.getNext(ResponseQueueReader.java:113)
	at com.google.cloud.bigtable.grpc.scanner.ResponseQueueReader.getNextMergedRow(ResponseQueueReader.java:64)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:64)
	at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:28)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:101)
	at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:42)
	at com.google.cloud.bigtable.hbase.adapters.BigtableResultScannerAdapter$1.next(BigtableResultScannerAdapter.java:43)
	at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:94)
	at com.google.common.collect.Iterators.size(Iterators.java:191)
	at com.google.common.collect.Iterables.size(Iterables.java:108)
```
