### ISSUE TITLE
Check version of HBase

### ISSUE THREAD

**Issue by reagere** [GoogleCloudPlatform/cloud-bigtable-client#485]
Hello,

We encounter some errors, mostly when we create a table or use admin.

The problem is: why there is a version check in bigtable?
I tried many version of the bigtable client, and was able to produce this error.

I hope you can help on this, because it blocks the access on bigtable.

Thank you

java.lang.RuntimeException: hbase-default.xml file seems to be for an older version of HBase (1.1.1), this version is Unknown
	at org.apache.hadoop.hbase.HBaseConfiguration.checkDefaultsVersion(HBaseConfiguration.java:71)
	at org.apache.hadoop.hbase.HBaseConfiguration.addHbaseResources(HBaseConfiguration.java:81)
	at org.apache.hadoop.hbase.HBaseConfiguration.create(HBaseConfiguration.java:96)
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:90)
	at com.accengage.globulus.util.bigtable.BigTableConnectionFactory.create(BigTableConnectionFactory.java:25)
	at com.accengage.globulus.util.bigtable.BigtableHelper.getConnection(BigtableHelper.java:109)
	at com.accengage.globulus.util.bigtable.BigtableHelper.getAdmin(BigtableHelper.java:528)
	at com.accengage.globulus.util.bigtable.IndexesHelper.<init>(IndexesHelper.java:53)

**Comment by lesv** [comment]
It actually looks like you aren't dealing w/ Cloud Bigtable at all.

In our [documentation](https://cloud.google.com/bigtable/docs/installing-hbase-shell#editing_configuration_files) you will see:

```<configuration>
  <property>
    <name>hbase.client.connection.impl</name>
    <value>com.google.cloud.bigtable.hbase1_0.BigtableConnection</value>
  </property>
  <property>
    <name>google.bigtable.cluster.name</name>
    <value>[YOUR-CLUSTER-ID]</value>
  </property>
  <property>
    <name>google.bigtable.project.id</name>
    <value>[YOUR-PROJECT-ID]</value>
  </property>
  <property>
    <name>google.bigtable.zone.name</name>
    <value>[YOUR-ZONE-NAME]</value>
  </property>
</configuration>```

The `hbase.client.connection.impl` needs to be either `com.google.cloud.bigtable.hbase1_0.BigtableConnection` for hbase 1.0.x or `com.google.cloud.bigtable.hbase1_1.BigtableConnection` for hbase 1.1.x.  The reason is that there are some api changes from 1.0 to 1.1 that affect us.

**Comment by sduskis** [comment]
hbase-default.xml is part of hbase-common-{version}.jar.  Can you explicitly include that dependency as part of your classpath?

**Comment by reagere** [comment]
Thank you.

I had some issues some time ago and checked the example here: https://github.com/GoogleCloudPlatform/cloud-bigtable-examples/blob/master/java/jetty-managed-vm/pom.xml.

I removed this dependency because it was not in this example.

bad luck...
