### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by reagere** [GoogleCloudPlatform/cloud-bigtable-client#486]
Hello,
With a fresh bigtable database, we serve put requests that will create a table if it is not found (exception case).

With large load, and emptied bigtable, we will create a lot of tables, and we have a too many open files error.

lsof shows large amount of lines.

[FATAL] 16-09-2015 16:12:43,670 org.apache.hadoop.conf.Configuration loadResource - error parsing conf hbase-site.xml
java.io.FileNotFoundException: /tmp/jetty-0.0.0.0-8080-globulus.war-_globulus-any-7404471105146041798.dir/webapp/WEB-INF/classes/hbase-site.xml (Too many open files)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at java.net.URL.openStream(URL.java:1038)
	at org.apache.hadoop.conf.Configuration.parse(Configuration.java:2171)
	at org.apache.hadoop.conf.Configuration.loadResource(Configuration.java:2242)
	at org.apache.hadoop.conf.Configuration.loadResources(Configuration.java:2205)
	at org.apache.hadoop.conf.Configuration.getProps(Configuration.java:2112)
	at org.apache.hadoop.conf.Configuration.get(Configuration.java:858)
	at org.apache.hadoop.conf.Configuration.getTrimmed(Configuration.java:877)
	at org.apache.hadoop.conf.Configuration.getBoolean(Configuration.java:1278)
	at org.apache.hadoop.hbase.HBaseConfiguration.checkDefaultsVersion(HBaseConfiguration.java:67)
	at org.apache.hadoop.hbase.HBaseConfiguration.addHbaseResources(HBaseConfiguration.java:81)
	at org.apache.hadoop.hbase.HBaseConfiguration.create(HBaseConfiguration.java:96)
	at org.apache.hadoop.hbase.HColumnDescriptor.<clinit>(HColumnDescriptor.java:147)
	at org.apache.hadoop.hbase.HTableDescriptor.<clinit>(HTableDescriptor.java:1456)
	at com.accengage.globulus.util.bigtable.BigtableHelper.createTable(BigtableHelper.java:78)

**Comment by sduskis** [comment]
I haven't come across this issue before, so I'm taking guesses.  It appears that you are configuring your environment through HBaseConfiguration.create(), or something like that.  HBaseConfiguration adds the following to the configuration:

    conf.addResource("hbase-default.xml");
    conf.addResource("hbase-site.xml");

The stack trace shows that you're not using hbase-site.xml, given the FileNotFoundException.  Given #485, I would venture to say that you're not using hbase-default either.

Instead of HBaseConfiguration.create(), you might want to opt with "new Configuration()."

For now, that's the best advice I can give.  I'd be glad to find out more about your situation to see if I can solve the issue.

**Comment by reagere** [comment]
Yes I was using the default HBaseConfiguration.create().
The file is present, but with the too many open files, maybe the exception is FileNotFound.

I added the configuration as you mentioned.
Seems to be good.

If I understand the fix, the resource is defined or loaded only once, with the specific configuration?
