### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by yaitskov** [GoogleCloudPlatform/cloud-bigtable-client#598]
Hi,

I started the same project after this weekend and discovered 
tests started to fail:

Exception is thrown again and again. It loops somewhere.

```
2015-12-14 17:32:21,993 WARN  [main] util.NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
2015-12-14 17:32:22,115 INFO  [main] grpc.BigtableSession: Opening connection for projectId audit-bt-dev-qa-1099, zoneId europe-west1-c, clusterId audit-qa, on data host bigtable.googleapis.com, table admin host bigtabletableadmin.googleapis.com.
2015-12-14 17:32:22,134 INFO  [BigtableSession-startup-0] grpc.BigtableSession: gRPC is using the JDK provider (alpn-boot jar)
2015-12-14 17:32:22,429 INFO  [bigtable-connection-shared-executor-pool1-t2] io.RefreshingOAuth2CredentialsInterceptor: Refreshing the OAuth token
2015-12-14 17:32:22,935 WARN  [bigtable-connection-shared-executor-pool1-t2] io.RefreshingOAuth2CredentialsInterceptor: Got an unexpected IOException when refreshing google credentials.
java.io.IOException: Error getting access token for service account: 
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:224)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.refreshCredentialsWithRetry(RefreshingOAuth2CredentialsInterceptor.java:268)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.doRefresh(RefreshingOAuth2CredentialsInterceptor.java:238)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor$1.run(RefreshingOAuth2CredentialsInterceptor.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.bigtable.repackaged.com.google.api.client.http.HttpResponseException: 400 Bad Request
{
  "error" : "invalid_grant"
}
	at com.google.bigtable.repackaged.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1054)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:222)
	... 6 more
2015-12-14 17:32:22,947 INFO  [bigtable-connection-shared-executor-pool1-t2] io.RefreshingOAuth2CredentialsInterceptor: Refreshing the OAuth token
2015-12-14 17:32:23,021 WARN  [bigtable-connection-shared-executor-pool1-t2] io.RefreshingOAuth2CredentialsInterceptor: Got an unexpected IOException when refreshing google credentials.
java.io.IOException: Error getting access token for service account: 
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:224)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.refreshCredentialsWithRetry(RefreshingOAuth2CredentialsInterceptor.java:268)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.doRefresh(RefreshingOAuth2CredentialsInterceptor.java:238)
	at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor$1.run(RefreshingOAuth2CredentialsInterceptor.java:166)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.bigtable.repackaged.com.google.api.client.http.HttpResponseException: 400 Bad Request
{
  "error" : "invalid_grant"
}
	at com.google.bigtable.repackaged.com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1054)
	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:222)
	... 6 more
2015-12-14 17:32:23,029 INFO  [bigtable-connection-shared-executor-pool1-t2] io.RefreshingOAuth2CredentialsInterceptor: Refreshing the OAuth token
2015-12-14 17:32:23,098 WARN  [bigtable-connection-shared-executor-pool1-t2] io.RefreshingOAuth2CredentialsInterceptor: Got an unexpected IOException when refreshing google credentials.
```

**Comment by sduskis** [comment]
This says that the credentials aren't configured properly.  You need to set credentials in your hbase-site.xml or programmatic Configuration object.  I'd venture that a json file is the right approach for an automated testing project.

The looping is a bit annoying.  I'll add in a test for 400 error codes, and not do automated retries in that case.

We need to do a better job documenting the crednetials.  For now, see https://cloud.google.com/bigtable/docs/hbase-shell-quickstart for how to generate the json file.  The code we use for processing credentials is at: https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-hbase/src/main/java/com/google/cloud/bigtable/hbase/BigtableOptionsFactory.java#L212

**Comment by yaitskov** [comment]
Thanks for the quick response.

I figured out that other team member invalided existing keys and created new one,
but I guess looping is not desired behavior.

Fail fast.

**Comment by sduskis** [comment]
For context, we do have intermittent problems with the credentials service when jobs are run at scale.  We want to retry in those cases.  We want to fail fast in others.  For now, I've erred on the side of retries.
