### ISSUE TITLE
FuzzyRowFilterAdapter is missing from FilterAdapter

### ISSUE THREAD

**Issue by ZubairNabi** [GoogleCloudPlatform/cloud-bigtable-client#616]
I've been trying to get `FuzzyRowFilter` to work, but out of the box I get the following exception:

```
Caused by: com.google.cloud.bigtable.hbase.adapters.filters.UnsupportedFilterException: Unsupported filters encountered: FilterSupportStatus{isSupported=false, reason='Don't know how to adapt Filter class 'class org.apache.hadoop.hbase.filter.FuzzyRowFilter''}
```

I can see that there's an adapter for it in the codebase but it's not in the filter map within `FileAdapter`. Putting it in the map causes the previous exception to obviously go away but then I get a dependency conflict:

```
Caused by: java.lang.NoSuchMethodError: org.apache.hadoop.hbase.protobuf.generated.HBaseProtos$BytesBytesPair.getFirst()Lcom/google/bigtable/repackaged/com/google/protobuf/ByteString;
	at com.google.cloud.bigtable.hbase.adapters.filters.FuzzyRowFilterAdapter.extractFuzzyRowFilterPairs(FuzzyRowFilterAdapter.java:90)
	at com.google.cloud.bigtable.hbase.adapters.filters.FuzzyRowFilterAdapter.adapt(FuzzyRowFilterAdapter.java:48)
	at com.google.cloud.bigtable.hbase.adapters.filters.FuzzyRowFilterAdapter.adapt(FuzzyRowFilterAdapter.java:39)
	at com.google.cloud.bigtable.hbase.adapters.filters.SingleFilterAdapter.adapt(SingleFilterAdapter.java:56)
	at com.google.cloud.bigtable.hbase.adapters.filters.FilterAdapter.adaptFilter(FilterAdapter.java:143)
	at com.google.cloud.bigtable.hbase.adapters.ScanAdapter.createUserFilter(ScanAdapter.java:116)
	at com.google.cloud.bigtable.hbase.adapters.ScanAdapter.buildFilter(ScanAdapter.java:77)
	at com.google.cloud.bigtable.hbase.adapters.ScanAdapter.adapt(ScanAdapter.java:94)
	at com.google.cloud.bigtable.hbase.adapters.HBaseRequestAdapter.adapt(HBaseRequestAdapter.java:70)
	at com.google.cloud.bigtable.hbase.BigtableTable.getScanner(BigtableTable.java:206)
```

This seems to be a subtle dependency issue due to the mismatch between protobuf versions used by HBase and BigTable but all shading attempts on my part have been futile so far. Any idea how I can side-step this issue?

**Comment by sduskis** [comment]
The dependency mismatch issue strikes again.  I'm going to have to mull over this one.  I'll see what I can do about this, since it's a bit tricky.  Perhaps we can use reflection instead of the FuzzyRowFilter proto conversion to get the fuzzyKeysData.  I'm not sure that I can fix this problem this week, given the short week, but I'll work on this as a high priority issue and hopefully submit a PR next week.

**Comment by sduskis** [comment]
There are quite a few issues with our current implementation of the FuzzyRowFilterAdapter.  Even once I fix the bugs, we won't be able to easily completely replicate the HBase FuzzyRowFilter implementation.  HBase will allow some cases that we won't; specifically, if the row size is smaller than the keys supplied to the filter.  In the meantime, you can use a FilterList of RowFilter with RegexStringComparator.

**Comment by ZubairNabi** [comment]
Thanks for looking into this.
And yes, I've gone ahead and replaced my `FuzzyRowFilter` with a `RegexStringComparator` based approach.

**Comment by sduskis** [comment]
I still didn't get to this. This will have to come in the next release.

**Comment by manolama** [comment]
+1 on this guy as I just learned how wonderfully useful this filter is.
