### ISSUE TITLE
"Sending GOAWAY failed" causing ListenableFuture to never be called

### ISSUE THREAD

**Issue by udoprog** [GoogleCloudPlatform/cloud-bigtable-client#767]
Hey,

This is with version 0.2.3 of the client.

I'm seeing errors associated to requests in my log*. I've noticed that the `ListenableFuture`s that I'm listening to for operations never complete (neither in error nor success).

I've verified this by maintaining a counter that I increment when I perform the requests, and decrement when the future completes for any reason. I note that when these errors occur, it doesn't decrease.

Looking through the code, I noticed the following that is a bit suspicious:
https://github.com/GoogleCloudPlatform/cloud-bigtable-client/blob/master/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/async/AsyncUnaryOperationObserver.java#L30
Naively it looks like there is a case where the future will never be completed (no data and `#onClose(...)` is called with an `ok` status). Maybe it's something deeper within gRPC. As of right now, I don't have a reliable way to reproduce it.

*: The error I'm seeing:
```
2016-03-26 04:53:01,564 ERROR c.s.h.b.i.n.h.c.h.Http2ConnectionHandler [bigtable-grpc-elg-50] Sending GOAWAY failed: lastStreamId '0', errorCode '2', debugData ''. Forcing shutdown of the connection. java.nio.channels.ClosedChannelException
2016-03-26 04:53:01,565 ERROR c.s.h.b.i.n.h.c.h.Http2ConnectionHandler [bigtable-grpc-elg-50] Sending GOAWAY failed: lastStreamId '0', errorCode '2', debugData 'refCnt: 0, decrement: 1'. Forcing shutdown of the connection. java.nio.channels.ClosedChannelException
2016-03-26 04:53:01,565 WARN c.s.h.b.i.n.c.DefaultChannelPipeline [bigtable-grpc-elg-50] An exception was thrown by a user handler while handling an exceptionCaught event java.lang.IllegalArgumentException: promise already done: Http2CodecUtil$SimpleChannelPromiseAggregator@4d2d16e(failure: java.nio.channels.ClosedChannelException)
        at com.spotify.heroic.bigtable.io.netty.channel.ChannelHandlerInvokerUtil.validatePromise(ChannelHandlerInvokerUtil.java:185)
        at com.spotify.heroic.bigtable.io.netty.channel.DefaultChannelHandlerInvoker.invokeWrite(DefaultChannelHandlerInvoker.java:340)
        at com.spotify.heroic.bigtable.io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:262)
        at com.spotify.heroic.bigtable.io.netty.handler.ssl.SslHandler.finishWrap(SslHandler.java:573)
        at com.spotify.heroic.bigtable.io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:560)
        at com.spotify.heroic.bigtable.io.netty.handler.ssl.SslHandler.flush(SslHandler.java:500)
        at com.spotify.heroic.bigtable.io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:165)
        at com.spotify.heroic.bigtable.io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:356)
        at com.spotify.heroic.bigtable.io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:269)
        at com.spotify.heroic.bigtable.io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:729)
        at com.spotify.heroic.bigtable.io.netty.handler.codec.http2.Http2ConnectionHandler.exceptionCaught(Http2ConnectionHandler.java:651)
        at io.grpc.netty.AbstractNettyHandler.exceptionCaught(AbstractNettyHandler.java:93)
        at com.spotify.heroic.bigtable.io.netty.channel.ChannelHandlerInvokerUtil.invokeExceptionCaughtNow(ChannelHandlerInvokerUtil.java:64)
        at com.spotify.heroic.bigtable.io.netty.channel.DefaultChannelHandlerInvoker.invokeExceptionCaught(DefaultChannelHandlerInvoker.java:120)
        at com.spotify.heroic.bigtable.io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:141)
        at com.spotify.heroic.bigtable.io.netty.handler.ssl.SslHandler.exceptionCaught(SslHandler.java:729)
        at com.spotify.heroic.bigtable.io.netty.channel.ChannelHandlerInvokerUtil.invokeExceptionCaughtNow(ChannelHandlerInvokerUtil.java:64)
        at com.spotify.heroic.bigtable.io.netty.channel.ChannelHandlerInvokerUtil.notifyHandlerException(ChannelHandlerInvokerUtil.java:219)
        at com.spotify.heroic.bigtable.io.netty.channel.ChannelHandlerInvokerUtil.invokeFlushNow(ChannelHandlerInvokerUtil.java:167)
        at com.spotify.heroic.bigtable.io.netty.channel.DefaultChannelHandlerInvoker.invokeFlush(DefaultChannelHandlerInvoker.java:356)
        at com.spotify.heroic.bigtable.io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:269)
        at com.spotify.heroic.bigtable.io.netty.handler.codec.http2.Http2ConnectionHandler.onError(Http2ConnectionHandler.java:729)
        at com.spotify.heroic.bigtable.io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledData.error(DefaultHttp2ConnectionEncoder.java:330)
        at com.spotify.heroic.bigtable.io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledBase.operationComplete(DefaultHttp2ConnectionEncoder.java:451)
        at com.spotify.heroic.bigtable.io.netty.handler.codec.http2.DefaultHttp2ConnectionEncoder$FlowControlledBase.operationComplete(DefaultHttp2ConnectionEncoder.java:423)
        at com.spotify.heroic.bigtable.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:680)
        at com.spotify.heroic.bigtable.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:603)
        at com.spotify.heroic.bigtable.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:563)
        at com.spotify.heroic.bigtable.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:424)
        at com.spotify.heroic.bigtable.io.netty.handler.codec.http2.Http2CodecUtil$SimpleChannelPromiseAggregator.tryFailure(Http2CodecUtil.java:251)
        at com.spotify.heroic.bigtable.io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:678)
        at com.spotify.heroic.bigtable.io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:298)
        at com.spotify.heroic.bigtable.io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:621)
        at com.spotify.heroic.bigtable.io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:646)
        at com.spotify.heroic.bigtable.io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:587)
        at com.spotify.heroic.bigtable.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.closeOnRead(AbstractNioByteChannel.java:70)
        at com.spotify.heroic.bigtable.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.handleReadException(AbstractNioByteChannel.java:89)
        at com.spotify.heroic.bigtable.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:136)
        at com.spotify.heroic.bigtable.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:510)
        at com.spotify.heroic.bigtable.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:467)
        at com.spotify.heroic.bigtable.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:381)
        at com.spotify.heroic.bigtable.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:353)
        at com.spotify.heroic.bigtable.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by garye** [comment]
I think the code you pointed out is first available in the 0.2.4 release. Is upgrading to 0.2.4 a possibility for you right now?
