### ISSUE TITLE
Support non-hbase Dataflow integration.

### ISSUE THREAD

**Issue by sduskis** [GoogleCloudPlatform/cloud-bigtable-client#799]
From a user: 

Thank you for all your great work in cloud-bigtable.
I'm wondering if you can implement something like CloudBigtableIO here: cloud-bigtable-client/bigtable-hbase-dataflow/src/main/java/com/google/cloud/bigtable/dataflow/

which doesn't need hbase (kinda ditching it) and use your grpc code here: cloud-bigtable-client/bigtable-client-core/src/main/java/com/google/cloud/bigtable/grpc/

once again, I appreciate your work very very much,

**Comment by sduskis** [comment]
That kind of exists already in the DataflowJavaSDK at https://github.com/GoogleCloudPlatform/DataflowJavaSDK/blob/master/sdk/src/main/java/com/google/cloud/dataflow/sdk/io/bigtable/BigtableIO.java.  It supports Protobufs instead of hbase objects.

Unfortunately, there are some limitations (no Pub/Sub as a Source support) and likely issues (you'll get unrecoverable exceptions after 1 hour of sustained use, or after 4 minutes of idle time).  The former is an intentional limit of the Dataflow implementation.  The latter was a bug in the 0.2.3 cloud bigtable client.

**Comment by jmehrdad** [comment]
Thank you for your note. Compiles just fine, but I have a tiny issue when I run.
Here is my build.gradle:
compile 'com.google.cloud.dataflow:google-cloud-dataflow-java-sdk-all:1.5.0',
            'com.google.protobuf:protobuf-java:3.0.0-beta-2',
            'com.google.protobuf:protobuf-java-util:3.0.0-beta-2'

Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.directExecutor()Ljava/util/concurrent/Executor;
	at io.grpc.internal.ClientCallImpl.<init>(ClientCallImpl.java:104)
	at io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:331)
	at io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:314)
	at com.google.cloud.dataflow.sdk.repackaged.com.google.cloud.bigtable.grpc.io.ReconnectingChannel$ChannelWrapper.start(ReconnectingChannel.java:124)
	at com.google.cloud.dataflow.sdk.repackaged.com.google.cloud.bigtable.grpc.io.ReconnectingChannel$DelayingCall.start(ReconnectingChannel.java:155)
	at com.google.cloud.dataflow.sdk.repackaged.com.google.cloud.bigtable.grpc.io.ChannelPool$1.checkedStart(ChannelPool.java:136)
	at io.grpc.ClientInterceptors$CheckedForwardingClientCall.start(ClientInterceptors.java:164)
	at io.grpc.stub.ClientCalls.startCall(ClientCalls.java:194)
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:174)
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:135)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:106)
	at com.google.bigtable.admin.table.v1.BigtableTableServiceGrpc$BigtableTableServiceBlockingStub.getTable(BigtableTableServiceGrpc.java:289)
	at com.google.cloud.dataflow.sdk.repackaged.com.google.cloud.bigtable.grpc.BigtableTableAdminGrpcClient.getTable(BigtableTableAdminGrpcClient.java:49)
	at com.google.cloud.dataflow.sdk.io.bigtable.BigtableServiceImpl.tableExists(BigtableServiceImpl.java:85)
	at com.google.cloud.dataflow.sdk.io.bigtable.BigtableIO$Write.validate(BigtableIO.java:410)
	at com.google.cloud.dataflow.sdk.io.bigtable.BigtableIO$Write.validate(BigtableIO.java:325)
	at com.google.cloud.dataflow.sdk.Pipeline.applyInternal(Pipeline.java:366)
	at com.google.cloud.dataflow.sdk.Pipeline.applyTransform(Pipeline.java:290)

**Comment by jmehrdad** [comment]
nvm, resolved it by enforcing guava-19.0. It works like a charm. thank you.

**Comment by sduskis** [comment]
We're leaving this open, because we need to upgrade to dataflow 1.5.1+

**Comment by sduskis** [comment]
We upgraded dataflow a while ago.  Closing.
