### ISSUE TITLE
Some threads don't check for interruption  - Credentials-Refresh-0 & bigtable-grpc-elg-0,

### ISSUE THREAD

**Issue by lesv** [GoogleCloudPlatform/cloud-bigtable-client#822]
I've redid the `HBase shell` quickstart to exec:java instead of exec:exec to use less RAM on DevShell - it fixes the hanging. (The only reason we were doing exec:exec was due to alpn-boot).

If there is something we can do about these, it would be great.  This is with 0.3.0 Client, and HBase 1.2.1
@hegemonic 
@sduskis FYI

```
[WARNING] thread Thread[Credentials-Refresh-0,5,org.jruby.Main] was interrupted but is still alive after waiting at least 15000msecs
[WARNING] thread Thread[Credentials-Refresh-0,5,org.jruby.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[bigtable-grpc-elg-0,5,org.jruby.Main] will linger despite being asked to die via interruption
[WARNING] thread Thread[threadDeathWatcher-2-1,1,org.jruby.Main] will linger despite being asked to die via interruption
[WARNING] NOTE: 3 thread(s) did not finish despite being asked to  via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=org.jruby.Main,maxpri=10]
java.lang.IllegalThreadStateException
        at java.lang.ThreadGroup.destroy(ThreadGroup.java:775)
        at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:328)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
```

**Comment by sduskis** [comment]
It's hard to understand what the problem is.  If you see this again, try to do a "kill -3 <the java pid>" to get a thread dump.

**Comment by sduskis** [comment]
This was a misconfiguration in your pom.xml where your cloud bigtable hbase version and your hbase client version were not compatible.

**Comment by lesv** [comment]
Yep - I think so.
