### ISSUE TITLE
Failed to load netty-tcnative

### ISSUE THREAD

**Issue by harbris** [GoogleCloudPlatform/cloud-bigtable-client#876]
- I wrote follow maven script in pom.xml.

```
<dependency>
	    <groupId>com.google.cloud.bigtable</groupId>
	    <artifactId>bigtable-hbase-1.1</artifactId>
	    <version>0.3.0</version>
</dependency>
```
```
<dependency>
      <groupId>io.netty</groupId>
      <artifactId>netty-tcnative-boringssl-static</artifactId>
      <version>1.1.33.Fork13</version>
      <classifier>${os.detected.classifier}</classifier>
</dependency>
```

- I connected using this method

```
public static void connect() throws IOException {
    Configuration c = HBaseConfiguration.create();

    c.setClass("hbase.client.connection.impl",
        com.google.cloud.bigtable.hbase1_1.BigtableConnection.class,
        org.apache.hadoop.hbase.client.Connection.class);   // Required for Cloud Bigtable

    c.set("google.bigtable.project.id", PROJECT_ID);
    c.set("google.bigtable.cluster.name", CLUSTER_ID);
    c.set("google.bigtable.zone.name", ZONE);

    connection = ConnectionFactory.createConnection(c);
  }
```
but It occured  this exeption 

[DEBUG] 2016-06-09 13:29:46 com.google.bigtable.repackaged.io.netty.handler.ssl.OpenSsl (Slf4JLogger.java:91) - Failed to load netty-tcnative; OpenSslEngine will be unavailable. See http://netty.io/wiki/forked-tomcat-native.html for more information.
java.lang.UnsatisfiedLinkError: no netty-tcnative in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864) ~[na:1.8.0_65]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[na:1.8.0_65]
	at java.lang.System.loadLibrary(System.java:1122) ~[na:1.8.0_65]
	at com.google.bigtable.repackaged.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:168) ~[bigtable-hbase-1.1-0.3.0.jar:na]
	at com.google.bigtable.repackaged.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:58) ~[bigtable-hbase-1.1-0.3.0.jar:na]
	at com.google.cloud.bigtable.grpc.BigtableSession.isAlpnProviderEnabled(BigtableSession.java:123) [bigtable-hbase-1.1-0.3.0.jar:na]
	at com.google.cloud.bigtable.grpc.BigtableSession.<init>(BigtableSession.java:237) [bigtable-hbase-1.1-0.3.0.jar:na]
	at org.apache.hadoop.hbase.client.AbstractBigtableConnection.<init>(AbstractBigtableConnection.java:123) [bigtable-hbase-1.1-0.3.0.jar:1.1.2]
	at com.google.cloud.bigtable.hbase1_1.BigtableConnection.<init>(BigtableConnection.java:42) [bigtable-hbase-1.1-0.3.0.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_65]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_65]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_65]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [na:1.8.0_65]
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:238) [hbase-client-1.1.2.jar:1.1.2]
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:218) [hbase-client-1.1.2.jar:1.1.2]
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119) [hbase-client-1.1.2.jar:1.1.2]
	at com.sil.docswave.config.BigtableHelper.connect(BigtableHelper.java:51) [classes/:na]
	at com.sil.docswave.config.BigtableHelper.contextInitialized(BigtableHelper.java:71) [classes/:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [catalina.jar:8.0.30]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [catalina.jar:8.0.30]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.30]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717) [catalina.jar:8.0.30]
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945) [catalina.jar:8.0.30]
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1795) [catalina.jar:8.0.30]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_65]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_65]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_65]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_65]

**Comment by sduskis** [comment]
Are you adding kr.motd.maven:os-maven-plugin to your pom.xml?  You need that if you're going to use the ${os.detected.classifier} variable.

Are you building and deploying the artifacts on the same OS?  If you build on one OS, and deploy on another, you end up with a netty-tcnative-boringssl-static for the OS on which you built the war file rather than the one you deploy on.  Different versions of netty-tcnative-boringssl-static have native libraries specific to an OS, and unfortunately, you can't use that jar on another OS.

This is a setup issue, and is difficult to debug based on a stack trace.  More setup information would be greatly appreciated.

As an FYI, [you can connect](https://cloud.google.com/bigtable/docs/connecting-hbase#settings-in-code) via the following code:
```
  public static void connect() throws IOException {
    connection = BigtableConfiguration.connect(PROJECT_ID, ZONE, CLUSTER_ID);
  }
```

**Comment by sduskis** [comment]
I'm closing this for now.  I don't think that there is anything actionable on our end.  Please feel free to reopen if this is still a problem.
