### ISSUE TITLE
Refresh Access token after days of usage

### ISSUE THREAD

**Issue by vc13819** [GoogleCloudPlatform/cloud-bigtable-client#911]
The error comes after days not hours. A restart always fixes it. Some problem with refreshing access tokens (look at the very end of the trace). Again some "repackaged" classes. Something escaped shading?

java.util.concurrent.ExecutionException: java.lang.RuntimeException: com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:188)
at com.yawasa.server.storage.RawTopicTable.freeFutures(RawTopicTable.java:187)
at com.yawasa.server.storage.RawTopicTable.get(RawTopicTable.java:105)
at com.yawasa.server.acl.AclTopicTable.getInternal(AclTopicTable.java:82)
at com.yawasa.server.acl.AclTopicTable.get(AclTopicTable.java:43)
at com.yawasa.server.ReadHandler.doPost(ReadHandler.java:42)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at com.google.apphosting.runtime.jetty9.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:50)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
at com.google.apphosting.vmruntime.jetty9.VmRuntimeWebAppContext.doScope(VmRuntimeWebAppContext.java:299)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:497)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:97)
at com.yawasa.server.storage.TopicPopulator.get(TopicPopulator.java:59)
at com.yawasa.server.storage.RawTopicTable.get(RawTopicTable.java:207)
at com.yawasa.server.storage.RawTopicTable.access$000(RawTopicTable.java:47)
at com.yawasa.server.storage.RawTopicTable$1.call(RawTopicTable.java:97)
at com.yawasa.server.storage.RawTopicTable$1.call(RawTopicTable.java:94)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
... 1 more
Caused by: com.google.cloud.bigtable.grpc.io.IOExceptionWithStatus: Error in response stream
at com.google.cloud.bigtable.grpc.scanner.ResultQueueEntry$ExceptionResultQueueEntry.getResponseOrThrow(ResultQueueEntry.java:66)
at com.google.cloud.bigtable.grpc.scanner.ResponseQueueReader.getNextMergedRow(ResponseQueueReader.java:69)
at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:42)
at com.google.cloud.bigtable.grpc.scanner.StreamingBigtableResultScanner.next(StreamingBigtableResultScanner.java:27)
at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:158)
at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.next(ResumingStreamingResultScanner.java:44)
at com.google.cloud.bigtable.hbase.adapters.BigtableResultScannerAdapter$1.next(BigtableResultScannerAdapter.java:43)
at org.apache.hadoop.hbase.client.AbstractClientScanner$1.hasNext(AbstractClientScanner.java:94)
... 11 more
Caused by: com.google.bigtable.repackaged.io.grpc.StatusRuntimeException: UNKNOWN
at com.google.bigtable.repackaged.io.grpc.Status.asRuntimeException(Status.java:431)
at com.google.cloud.bigtable.grpc.scanner.ReadRowsResponseListener.onClose(ReadRowsResponseListener.java:72)
at com.google.bigtable.repackaged.io.grpc.ClientInterceptors$CheckedForwardingClientCall.start(ClientInterceptors.java:172)
at com.google.cloud.bigtable.grpc.async.BigtableAsyncUtilities$Default.start(BigtableAsyncUtilities.java:110)
at com.google.cloud.bigtable.grpc.async.BigtableAsyncUtilities$Default.asyncServerStreamingCall(BigtableAsyncUtilities.java:94)
at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.streamRows(BigtableDataGrpcClient.java:364)
at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.access$100(BigtableDataGrpcClient.java:75)
at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient$5.createScanner(BigtableDataGrpcClient.java:153)
at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.(ResumingStreamingResultScanner.java:133)
at com.google.cloud.bigtable.grpc.scanner.ResumingStreamingResultScanner.(ResumingStreamingResultScanner.java:122)
at com.google.cloud.bigtable.grpc.BigtableDataGrpcClient.readRows(BigtableDataGrpcClient.java:330)
at com.google.cloud.bigtable.hbase.BigtableTable.getScanner(BigtableTable.java:214)
... 11 more
Caused by: java.io.IOException: Could not read headers
at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.refreshCredentialsWithRetry(RefreshingOAuth2CredentialsInterceptor.java:318)
at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.doRefresh(RefreshingOAuth2CredentialsInterceptor.java:256)
at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.syncRefresh(RefreshingOAuth2CredentialsInterceptor.java:192)
at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.getHeader(RefreshingOAuth2CredentialsInterceptor.java:219)
at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.updateHeaders(RefreshingOAuth2CredentialsInterceptor.java:177)
at com.google.cloud.bigtable.grpc.io.ChannelPool$1.checkedStart(ChannelPool.java:140)
at com.google.bigtable.repackaged.io.grpc.ClientInterceptors$CheckedForwardingClientCall.start(ClientInterceptors.java:164)
... 20 more
Caused by: com.google.apphosting.api.ApiProxy$ArgumentException: An error occurred parsing (locally or remotely) the arguments to APP_IDENTITY_SERVICE.GetAccessToken().
at com.google.apphosting.vmruntime.VmApiProxyDelegate.convertApiResponseRpcErrorToException(VmApiProxyDelegate.java:399)
at com.google.apphosting.vmruntime.VmApiProxyDelegate.convertRemoteError(VmApiProxyDelegate.java:343)
at com.google.apphosting.vmruntime.VmApiProxyDelegate.runSyncCall(VmApiProxyDelegate.java:187)
at com.google.apphosting.vmruntime.VmApiProxyDelegate.makeApiCall(VmApiProxyDelegate.java:154)

11:51:40.187

at com.google.apphosting.vmruntime.VmApiProxyDelegate.makeSyncCallWithTimeout(VmApiProxyDelegate.java:128)
at com.google.apphosting.vmruntime.VmApiProxyDelegate.makeSyncCall(VmApiProxyDelegate.java:117)
at com.google.apphosting.vmruntime.VmApiProxyDelegate.makeSyncCall(VmApiProxyDelegate.java:60)
at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:114)
at com.google.apphosting.api.ApiProxy.makeSyncCall(ApiProxy.java:66)
at com.google.appengine.api.appidentity.AppIdentityServiceImpl.getAccessTokenUncached(AppIdentityServiceImpl.java:232)
at com.google.appengine.api.appidentity.AppIdentityServiceImpl.getAccessToken(AppIdentityServiceImpl.java:291)
at com.google.bigtable.repackaged.com.google.auth.appengine.AppEngineCredentials.refreshAccessToken(AppEngineCredentials.java:77)
at com.google.cloud.bigtable.grpc.io.RefreshingOAuth2CredentialsInterceptor.refreshCredentialsWithRetry(RefreshingOAuth2CredentialsInterceptor.java:286)

**Comment by sduskis** [comment]
This doesn't seem to be an issue with Cloud Bigtable.  Cloud Bigtable needs to get credentials from what ever environment it's hosted in.  In this case, appengine.  It looks like the credentials come from com.google.appengine:appengine-java-vm-runtime, which cloud-bigtable does not import directly, but seems to be a dependency of com.google.auth:google-auth-library-appengine which cloud-bigtable does import.

I'm not completely sure about the fix here.  Let's start with the easy things.  What version of cloud bigtable are you on?

**Comment by vc13819** [comment]
0.3.0

**Comment by lesv** [comment]
I think we are discussing this in #750, so I'm going to close this.
